// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode CherokeeSupplement code points.

const lo: u21 = 0xab70;
const hi: u21 = 0xabbf;

pub fn isCherokeeSupplement(cp: u21) bool {
    if (cp < lo or cp > hi) return false;
    return switch (cp) {
        0xab70...0xabbf => true,
        else => false,
    };
}