// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode CJKCompatibilityIdeographsSupplement code points.

const lo: u21 = 0x2f800;
const hi: u21 = 0x2fa1f;

pub fn isCJKCompatibilityIdeographsSupplement(cp: u21) bool {
    if (cp < lo or cp > hi) return false;
    return switch (cp) {
        0x2f800...0x2fa1f => true,
        else => false,
    };
}