// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode CJKCompatibilityIdeographs code points.

const lo: u21 = 0xf900;
const hi: u21 = 0xfaff;

pub fn isCJKCompatibilityIdeographs(cp: u21) bool {
    if (cp < lo or cp > hi) return false;
    return switch (cp) {
        0xf900...0xfaff => true,
        else => false,
    };
}