// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode CombiningHalfMarks code points.

const lo: u21 = 0xfe20;
const hi: u21 = 0xfe2f;

pub fn isCombiningHalfMarks(cp: u21) bool {
    if (cp < lo or cp > hi) return false;
    return switch (cp) {
        0xfe20...0xfe2f => true,
        else => false,
    };
}