// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode CuneiformNumbersandPunctuation code points.

const lo: u21 = 0x12400;
const hi: u21 = 0x1247f;

pub fn isCuneiformNumbersandPunctuation(cp: u21) bool {
    if (cp < lo or cp > hi) return false;
    return switch (cp) {
        0x12400...0x1247f => true,
        else => false,
    };
}