// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Mandaic code points.

const lo: u21 = 0x840;
const hi: u21 = 0x85f;

pub fn isMandaic(cp: u21) bool {
    if (cp < lo or cp > hi) return false;
    return switch (cp) {
        0x840...0x85f => true,
        else => false,
    };
}