// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Arabic code points.

const std = @import("std");
const mem = std.mem;

const Arabic = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 1536,
hi: u21 = 126705,

pub fn init(allocator: *mem.Allocator) !Arabic {
    var instance = Arabic{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 125170),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 0;
    while (index <= 4) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6;
    while (index <= 8) : (index += 1) {
        instance.array[index] = true;
    }
    index = 9;
    while (index <= 10) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[11] = true;
    instance.array[13] = true;
    index = 14;
    while (index <= 15) : (index += 1) {
        instance.array[index] = true;
    }
    index = 16;
    while (index <= 26) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[28] = true;
    instance.array[30] = true;
    index = 32;
    while (index <= 63) : (index += 1) {
        instance.array[index] = true;
    }
    index = 65;
    while (index <= 74) : (index += 1) {
        instance.array[index] = true;
    }
    index = 86;
    while (index <= 95) : (index += 1) {
        instance.array[index] = true;
    }
    index = 96;
    while (index <= 105) : (index += 1) {
        instance.array[index] = true;
    }
    index = 106;
    while (index <= 109) : (index += 1) {
        instance.array[index] = true;
    }
    index = 110;
    while (index <= 111) : (index += 1) {
        instance.array[index] = true;
    }
    index = 113;
    while (index <= 211) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[212] = true;
    instance.array[213] = true;
    index = 214;
    while (index <= 220) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[222] = true;
    index = 223;
    while (index <= 228) : (index += 1) {
        instance.array[index] = true;
    }
    index = 229;
    while (index <= 230) : (index += 1) {
        instance.array[index] = true;
    }
    index = 231;
    while (index <= 232) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[233] = true;
    index = 234;
    while (index <= 237) : (index += 1) {
        instance.array[index] = true;
    }
    index = 238;
    while (index <= 239) : (index += 1) {
        instance.array[index] = true;
    }
    index = 240;
    while (index <= 249) : (index += 1) {
        instance.array[index] = true;
    }
    index = 250;
    while (index <= 252) : (index += 1) {
        instance.array[index] = true;
    }
    index = 253;
    while (index <= 254) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[255] = true;
    index = 336;
    while (index <= 383) : (index += 1) {
        instance.array[index] = true;
    }
    index = 672;
    while (index <= 692) : (index += 1) {
        instance.array[index] = true;
    }
    index = 694;
    while (index <= 711) : (index += 1) {
        instance.array[index] = true;
    }
    index = 723;
    while (index <= 737) : (index += 1) {
        instance.array[index] = true;
    }
    index = 739;
    while (index <= 767) : (index += 1) {
        instance.array[index] = true;
    }
    index = 62800;
    while (index <= 62897) : (index += 1) {
        instance.array[index] = true;
    }
    index = 62898;
    while (index <= 62913) : (index += 1) {
        instance.array[index] = true;
    }
    index = 62931;
    while (index <= 63293) : (index += 1) {
        instance.array[index] = true;
    }
    index = 63312;
    while (index <= 63375) : (index += 1) {
        instance.array[index] = true;
    }
    index = 63378;
    while (index <= 63431) : (index += 1) {
        instance.array[index] = true;
    }
    index = 63472;
    while (index <= 63483) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[63484] = true;
    instance.array[63485] = true;
    index = 63600;
    while (index <= 63604) : (index += 1) {
        instance.array[index] = true;
    }
    index = 63606;
    while (index <= 63740) : (index += 1) {
        instance.array[index] = true;
    }
    index = 67680;
    while (index <= 67710) : (index += 1) {
        instance.array[index] = true;
    }
    index = 124928;
    while (index <= 124931) : (index += 1) {
        instance.array[index] = true;
    }
    index = 124933;
    while (index <= 124959) : (index += 1) {
        instance.array[index] = true;
    }
    index = 124961;
    while (index <= 124962) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[124964] = true;
    instance.array[124967] = true;
    index = 124969;
    while (index <= 124978) : (index += 1) {
        instance.array[index] = true;
    }
    index = 124980;
    while (index <= 124983) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[124985] = true;
    instance.array[124987] = true;
    instance.array[124994] = true;
    instance.array[124999] = true;
    instance.array[125001] = true;
    instance.array[125003] = true;
    index = 125005;
    while (index <= 125007) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125009;
    while (index <= 125010) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[125012] = true;
    instance.array[125015] = true;
    instance.array[125017] = true;
    instance.array[125019] = true;
    instance.array[125021] = true;
    instance.array[125023] = true;
    index = 125025;
    while (index <= 125026) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[125028] = true;
    index = 125031;
    while (index <= 125034) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125036;
    while (index <= 125042) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125044;
    while (index <= 125047) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125049;
    while (index <= 125052) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[125054] = true;
    index = 125056;
    while (index <= 125065) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125067;
    while (index <= 125083) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125089;
    while (index <= 125091) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125093;
    while (index <= 125097) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125099;
    while (index <= 125115) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125168;
    while (index <= 125169) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Arabic) void {
    self.allocator.free(self.array);
}

// isArabic checks if cp is of the kind Arabic.
pub fn isArabic(self: Arabic, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
