// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Balinese code points.

const std = @import("std");
const mem = std.mem;

const Balinese = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 6916,
hi: u21 = 74649,

pub fn init(allocator: *mem.Allocator) !Balinese {
    var instance = Balinese{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 67734),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 2097148;
    while (index <= 2097151) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[0] = true;
    index = 1;
    while (index <= 47) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[48] = true;
    instance.array[49] = true;
    index = 50;
    while (index <= 54) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[55] = true;
    instance.array[56] = true;
    index = 57;
    while (index <= 61) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[62] = true;
    index = 63;
    while (index <= 64) : (index += 1) {
        instance.array[index] = true;
    }
    index = 65;
    while (index <= 71) : (index += 1) {
        instance.array[index] = true;
    }
    index = 76;
    while (index <= 85) : (index += 1) {
        instance.array[index] = true;
    }
    index = 86;
    while (index <= 92) : (index += 1) {
        instance.array[index] = true;
    }
    index = 93;
    while (index <= 102) : (index += 1) {
        instance.array[index] = true;
    }
    index = 103;
    while (index <= 111) : (index += 1) {
        instance.array[index] = true;
    }
    index = 112;
    while (index <= 120) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Balinese) void {
    self.allocator.free(self.array);
}

// isBalinese checks if cp is of the kind Balinese.
pub fn isBalinese(self: Balinese, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
