// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Bamum code points.

const std = @import("std");
const mem = std.mem;

const Bamum = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 42726,
hi: u21 = 92728,

pub fn init(allocator: *mem.Allocator) !Bamum {
    var instance = Bamum{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 50003),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 2097082;
    while (index <= 2097151) : (index += 1) {
        instance.array[index] = true;
    }
    index = 0;
    while (index <= 9) : (index += 1) {
        instance.array[index] = true;
    }
    index = 10;
    while (index <= 11) : (index += 1) {
        instance.array[index] = true;
    }
    index = 12;
    while (index <= 17) : (index += 1) {
        instance.array[index] = true;
    }
    index = 49434;
    while (index <= 50002) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Bamum) void {
    self.allocator.free(self.array);
}

// isBamum checks if cp is of the kind Bamum.
pub fn isBamum(self: Bamum, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
