// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Buginese code points.

const std = @import("std");
const mem = std.mem;

const Buginese = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 994,
hi: u21 = 6687,

pub fn init(allocator: *mem.Allocator) !Buginese {
    var instance = Buginese{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 5694),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 5662;
    while (index <= 5684) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5685;
    while (index <= 5686) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5687;
    while (index <= 5688) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[5689] = true;
    index = 5692;
    while (index <= 5693) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Buginese) void {
    self.allocator.free(self.array);
}

// isBuginese checks if cp is of the kind Buginese.
pub fn isBuginese(self: Buginese, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
