// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Cham code points.

const std = @import("std");
const mem = std.mem;

const Cham = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 43520,
hi: u21 = 43615,

pub fn init(allocator: *mem.Allocator) !Cham {
    var instance = Cham{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 96),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 0;
    while (index <= 40) : (index += 1) {
        instance.array[index] = true;
    }
    index = 41;
    while (index <= 46) : (index += 1) {
        instance.array[index] = true;
    }
    index = 47;
    while (index <= 48) : (index += 1) {
        instance.array[index] = true;
    }
    index = 49;
    while (index <= 50) : (index += 1) {
        instance.array[index] = true;
    }
    index = 51;
    while (index <= 52) : (index += 1) {
        instance.array[index] = true;
    }
    index = 53;
    while (index <= 54) : (index += 1) {
        instance.array[index] = true;
    }
    index = 64;
    while (index <= 66) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[67] = true;
    index = 68;
    while (index <= 75) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[76] = true;
    instance.array[77] = true;
    index = 80;
    while (index <= 89) : (index += 1) {
        instance.array[index] = true;
    }
    index = 92;
    while (index <= 95) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Cham) void {
    self.allocator.free(self.array);
}

// isCham checks if cp is of the kind Cham.
pub fn isCham(self: Cham, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
