// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Cypriot code points.

const std = @import("std");
const mem = std.mem;

const Cypriot = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 10240,
hi: u21 = 67647,

pub fn init(allocator: *mem.Allocator) !Cypriot {
    var instance = Cypriot{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 57408),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 57344;
    while (index <= 57349) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[57352] = true;
    index = 57354;
    while (index <= 57397) : (index += 1) {
        instance.array[index] = true;
    }
    index = 57399;
    while (index <= 57400) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[57404] = true;
    instance.array[57407] = true;

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Cypriot) void {
    self.allocator.free(self.array);
}

// isCypriot checks if cp is of the kind Cypriot.
pub fn isCypriot(self: Cypriot, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
