// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Duployan code points.

const std = @import("std");
const mem = std.mem;

const Duployan = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 66816,
hi: u21 = 113823,

pub fn init(allocator: *mem.Allocator) !Duployan {
    var instance = Duployan{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 47008),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 46848;
    while (index <= 46954) : (index += 1) {
        instance.array[index] = true;
    }
    index = 46960;
    while (index <= 46972) : (index += 1) {
        instance.array[index] = true;
    }
    index = 46976;
    while (index <= 46984) : (index += 1) {
        instance.array[index] = true;
    }
    index = 46992;
    while (index <= 47001) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[47004] = true;
    index = 47005;
    while (index <= 47006) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[47007] = true;

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Duployan) void {
    self.allocator.free(self.array);
}

// isDuployan checks if cp is of the kind Duployan.
pub fn isDuployan(self: Duployan, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
