// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Gunjala_Gondi code points.

const std = @import("std");
const mem = std.mem;

const GunjalaGondi = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 73056,
hi: u21 = 73129,

pub fn init(allocator: *mem.Allocator) !GunjalaGondi {
    var instance = GunjalaGondi{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 74),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 0;
    while (index <= 5) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7;
    while (index <= 8) : (index += 1) {
        instance.array[index] = true;
    }
    index = 10;
    while (index <= 41) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42;
    while (index <= 46) : (index += 1) {
        instance.array[index] = true;
    }
    index = 48;
    while (index <= 49) : (index += 1) {
        instance.array[index] = true;
    }
    index = 51;
    while (index <= 52) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[53] = true;
    instance.array[54] = true;
    instance.array[55] = true;
    instance.array[56] = true;
    index = 64;
    while (index <= 73) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *GunjalaGondi) void {
    self.allocator.free(self.array);
}

// isGunjalaGondi checks if cp is of the kind Gunjala_Gondi.
pub fn isGunjalaGondi(self: GunjalaGondi, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
