// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Kharoshthi code points.

const std = @import("std");
const mem = std.mem;

const Kharoshthi = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 6912,
hi: u21 = 68184,

pub fn init(allocator: *mem.Allocator) !Kharoshthi {
    var instance = Kharoshthi{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 61273),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    instance.array[61184] = true;
    index = 61185;
    while (index <= 61187) : (index += 1) {
        instance.array[index] = true;
    }
    index = 61189;
    while (index <= 61190) : (index += 1) {
        instance.array[index] = true;
    }
    index = 61196;
    while (index <= 61199) : (index += 1) {
        instance.array[index] = true;
    }
    index = 61200;
    while (index <= 61203) : (index += 1) {
        instance.array[index] = true;
    }
    index = 61205;
    while (index <= 61207) : (index += 1) {
        instance.array[index] = true;
    }
    index = 61209;
    while (index <= 61237) : (index += 1) {
        instance.array[index] = true;
    }
    index = 61240;
    while (index <= 61242) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[61247] = true;
    index = 61248;
    while (index <= 61256) : (index += 1) {
        instance.array[index] = true;
    }
    index = 61264;
    while (index <= 61272) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Kharoshthi) void {
    self.allocator.free(self.array);
}

// isKharoshthi checks if cp is of the kind Kharoshthi.
pub fn isKharoshthi(self: Kharoshthi, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
