// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Khojki code points.

const std = @import("std");
const mem = std.mem;

const Khojki = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 67072,
hi: u21 = 70206,

pub fn init(allocator: *mem.Allocator) !Khojki {
    var instance = Khojki{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 3135),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 3072;
    while (index <= 3089) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3091;
    while (index <= 3115) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3116;
    while (index <= 3118) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3119;
    while (index <= 3121) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3122;
    while (index <= 3123) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3124] = true;
    instance.array[3125] = true;
    index = 3126;
    while (index <= 3127) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3128;
    while (index <= 3133) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3134] = true;

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Khojki) void {
    self.allocator.free(self.array);
}

// isKhojki checks if cp is of the kind Khojki.
pub fn isKhojki(self: Khojki, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
