// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Modi code points.

const std = @import("std");
const mem = std.mem;

const Modi = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 71216,
hi: u21 = 92766,

pub fn init(allocator: *mem.Allocator) !Modi {
    var instance = Modi{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 21551),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 2097104;
    while (index <= 2097151) : (index += 1) {
        instance.array[index] = true;
    }
    index = 0;
    while (index <= 2) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3;
    while (index <= 10) : (index += 1) {
        instance.array[index] = true;
    }
    index = 11;
    while (index <= 12) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[13] = true;
    instance.array[14] = true;
    index = 15;
    while (index <= 16) : (index += 1) {
        instance.array[index] = true;
    }
    index = 17;
    while (index <= 19) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[20] = true;
    index = 32;
    while (index <= 41) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Modi) void {
    self.allocator.free(self.array);
}

// isModi checks if cp is of the kind Modi.
pub fn isModi(self: Modi, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
