// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Nko code points.

const std = @import("std");
const mem = std.mem;

const Nko = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 1994,
hi: u21 = 7041,

pub fn init(allocator: *mem.Allocator) !Nko {
    var instance = Nko{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 5048),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 2097142;
    while (index <= 2097151) : (index += 1) {
        instance.array[index] = true;
    }
    index = 0;
    while (index <= 32) : (index += 1) {
        instance.array[index] = true;
    }
    index = 33;
    while (index <= 41) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42;
    while (index <= 43) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[44] = true;
    index = 45;
    while (index <= 47) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[48] = true;
    instance.array[51] = true;
    index = 52;
    while (index <= 53) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Nko) void {
    self.allocator.free(self.array);
}

// isNko checks if cp is of the kind Nko.
pub fn isNko(self: Nko, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
