// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Nko code points.

const std = @import("std");
const mem = std.mem;

const Nko = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 1984,
hi: u21 = 2047,

pub fn init(allocator: *mem.Allocator) !Nko {
    var instance = Nko{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 64),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 0;
    while (index <= 9) : (index += 1) {
        instance.array[index] = true;
    }
    index = 10;
    while (index <= 42) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43;
    while (index <= 51) : (index += 1) {
        instance.array[index] = true;
    }
    index = 52;
    while (index <= 53) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[54] = true;
    index = 55;
    while (index <= 57) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[58] = true;
    instance.array[61] = true;
    index = 62;
    while (index <= 63) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Nko) void {
    self.allocator.free(self.array);
}

// isNko checks if cp is of the kind Nko.
pub fn isNko(self: Nko, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
