// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Pahawh_Hmong code points.

const std = @import("std");
const mem = std.mem;

const PahawhHmong = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 92928,
hi: u21 = 93071,

pub fn init(allocator: *mem.Allocator) !PahawhHmong {
    var instance = PahawhHmong{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 144),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 0;
    while (index <= 47) : (index += 1) {
        instance.array[index] = true;
    }
    index = 48;
    while (index <= 54) : (index += 1) {
        instance.array[index] = true;
    }
    index = 55;
    while (index <= 59) : (index += 1) {
        instance.array[index] = true;
    }
    index = 60;
    while (index <= 63) : (index += 1) {
        instance.array[index] = true;
    }
    index = 64;
    while (index <= 67) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[68] = true;
    instance.array[69] = true;
    index = 80;
    while (index <= 89) : (index += 1) {
        instance.array[index] = true;
    }
    index = 91;
    while (index <= 97) : (index += 1) {
        instance.array[index] = true;
    }
    index = 99;
    while (index <= 119) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125;
    while (index <= 143) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *PahawhHmong) void {
    self.allocator.free(self.array);
}

// isPahawhHmong checks if cp is of the kind Pahawh_Hmong.
pub fn isPahawhHmong(self: PahawhHmong, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
