// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Siddham code points.

const std = @import("std");
const mem = std.mem;

const Siddham = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 70320,
hi: u21 = 71133,

pub fn init(allocator: *mem.Allocator) !Siddham {
    var instance = Siddham{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 814),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 720;
    while (index <= 766) : (index += 1) {
        instance.array[index] = true;
    }
    index = 767;
    while (index <= 769) : (index += 1) {
        instance.array[index] = true;
    }
    index = 770;
    while (index <= 773) : (index += 1) {
        instance.array[index] = true;
    }
    index = 776;
    while (index <= 779) : (index += 1) {
        instance.array[index] = true;
    }
    index = 780;
    while (index <= 781) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[782] = true;
    index = 783;
    while (index <= 784) : (index += 1) {
        instance.array[index] = true;
    }
    index = 785;
    while (index <= 807) : (index += 1) {
        instance.array[index] = true;
    }
    index = 808;
    while (index <= 811) : (index += 1) {
        instance.array[index] = true;
    }
    index = 812;
    while (index <= 813) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Siddham) void {
    self.allocator.free(self.array);
}

// isSiddham checks if cp is of the kind Siddham.
pub fn isSiddham(self: Siddham, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
