// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Vai code points.

const std = @import("std");
const mem = std.mem;

const Vai = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 42240,
hi: u21 = 42539,

pub fn init(allocator: *mem.Allocator) !Vai {
    var instance = Vai{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 300),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 0;
    while (index <= 267) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[268] = true;
    index = 269;
    while (index <= 271) : (index += 1) {
        instance.array[index] = true;
    }
    index = 272;
    while (index <= 287) : (index += 1) {
        instance.array[index] = true;
    }
    index = 288;
    while (index <= 297) : (index += 1) {
        instance.array[index] = true;
    }
    index = 298;
    while (index <= 299) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Vai) void {
    self.allocator.free(self.array);
}

// isVai checks if cp is of the kind Vai.
pub fn isVai(self: Vai, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
