// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode IDS_Trinary_Operator code points.

const std = @import("std");
const mem = std.mem;

const IDSTrinaryOperator = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 11904,
hi: u21 = 11929,

pub fn init(allocator: *mem.Allocator) !IDSTrinaryOperator {
    var instance = IDSTrinaryOperator{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 26),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 370;
    while (index <= 371) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *IDSTrinaryOperator) void {
    self.allocator.free(self.array);
}

// isIDSTrinaryOperator checks if cp is of the kind IDS_Trinary_Operator.
pub fn isIDSTrinaryOperator(self: IDSTrinaryOperator, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
