// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Other_Math code points.

const std = @import("std");
const mem = std.mem;

const OtherMath = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 94,
hi: u21 = 126651,

pub fn init(allocator: *mem.Allocator) !OtherMath {
    var instance = OtherMath{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 126558),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    instance.array[0] = true;
    index = 882;
    while (index <= 884) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[887] = true;
    index = 914;
    while (index <= 915) : (index += 1) {
        instance.array[index] = true;
    }
    index = 918;
    while (index <= 919) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8120] = true;
    index = 8148;
    while (index <= 8150) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8162] = true;
    index = 8195;
    while (index <= 8198) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8223] = true;
    instance.array[8224] = true;
    instance.array[8239] = true;
    instance.array[8240] = true;
    index = 8306;
    while (index <= 8318) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8323] = true;
    index = 8327;
    while (index <= 8328) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8333;
    while (index <= 8337) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8356] = true;
    instance.array[8361] = true;
    index = 8364;
    while (index <= 8373) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8375] = true;
    index = 8379;
    while (index <= 8383) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8390] = true;
    instance.array[8394] = true;
    instance.array[8395] = true;
    index = 8398;
    while (index <= 8399) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8401;
    while (index <= 8403) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8405;
    while (index <= 8406) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8407;
    while (index <= 8410) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8414;
    while (index <= 8417) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8423;
    while (index <= 8427) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8503;
    while (index <= 8507) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8510;
    while (index <= 8513) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8515;
    while (index <= 8516) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8518;
    while (index <= 8519) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8521] = true;
    index = 8523;
    while (index <= 8527) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8530;
    while (index <= 8531) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8536;
    while (index <= 8537) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8542;
    while (index <= 8559) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8562;
    while (index <= 8563) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8565] = true;
    index = 8567;
    while (index <= 8573) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8575] = true;
    index = 8582;
    while (index <= 8583) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8874] = true;
    instance.array[8875] = true;
    instance.array[8876] = true;
    instance.array[8877] = true;
    index = 9046;
    while (index <= 9047) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[9049] = true;
    instance.array[9074] = true;
    instance.array[9092] = true;
    index = 9538;
    while (index <= 9539) : (index += 1) {
        instance.array[index] = true;
    }
    index = 9552;
    while (index <= 9560) : (index += 1) {
        instance.array[index] = true;
    }
    index = 9566;
    while (index <= 9570) : (index += 1) {
        instance.array[index] = true;
    }
    index = 9576;
    while (index <= 9577) : (index += 1) {
        instance.array[index] = true;
    }
    index = 9580;
    while (index <= 9581) : (index += 1) {
        instance.array[index] = true;
    }
    index = 9585;
    while (index <= 9589) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[9604] = true;
    instance.array[9606] = true;
    index = 9609;
    while (index <= 9614) : (index += 1) {
        instance.array[index] = true;
    }
    index = 9639;
    while (index <= 9640) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[9698] = true;
    instance.array[9700] = true;
    index = 9730;
    while (index <= 9733) : (index += 1) {
        instance.array[index] = true;
    }
    index = 9743;
    while (index <= 9744) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[10087] = true;
    instance.array[10088] = true;
    instance.array[10120] = true;
    instance.array[10121] = true;
    instance.array[10122] = true;
    instance.array[10123] = true;
    instance.array[10124] = true;
    instance.array[10125] = true;
    instance.array[10126] = true;
    instance.array[10127] = true;
    instance.array[10128] = true;
    instance.array[10129] = true;
    instance.array[10533] = true;
    instance.array[10534] = true;
    instance.array[10535] = true;
    instance.array[10536] = true;
    instance.array[10537] = true;
    instance.array[10538] = true;
    instance.array[10539] = true;
    instance.array[10540] = true;
    instance.array[10541] = true;
    instance.array[10542] = true;
    instance.array[10543] = true;
    instance.array[10544] = true;
    instance.array[10545] = true;
    instance.array[10546] = true;
    instance.array[10547] = true;
    instance.array[10548] = true;
    instance.array[10549] = true;
    instance.array[10550] = true;
    instance.array[10551] = true;
    instance.array[10552] = true;
    instance.array[10553] = true;
    instance.array[10554] = true;
    instance.array[10618] = true;
    instance.array[10619] = true;
    instance.array[10620] = true;
    instance.array[10621] = true;
    instance.array[10654] = true;
    instance.array[10655] = true;
    instance.array[65027] = true;
    instance.array[65029] = true;
    instance.array[65034] = true;
    instance.array[65246] = true;
    instance.array[65248] = true;
    index = 119714;
    while (index <= 119798) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119800;
    while (index <= 119870) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119872;
    while (index <= 119873) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[119876] = true;
    index = 119879;
    while (index <= 119880) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119883;
    while (index <= 119886) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119888;
    while (index <= 119899) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[119901] = true;
    index = 119903;
    while (index <= 119909) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119911;
    while (index <= 119975) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119977;
    while (index <= 119980) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119983;
    while (index <= 119990) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119992;
    while (index <= 119998) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120000;
    while (index <= 120027) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120029;
    while (index <= 120032) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120034;
    while (index <= 120038) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[120040] = true;
    index = 120044;
    while (index <= 120050) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120052;
    while (index <= 120391) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120394;
    while (index <= 120418) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120420;
    while (index <= 120444) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120446;
    while (index <= 120476) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120478;
    while (index <= 120502) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120504;
    while (index <= 120534) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120536;
    while (index <= 120560) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120562;
    while (index <= 120592) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120594;
    while (index <= 120618) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120620;
    while (index <= 120650) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120652;
    while (index <= 120676) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120678;
    while (index <= 120685) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120688;
    while (index <= 120737) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126370;
    while (index <= 126373) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126375;
    while (index <= 126401) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126403;
    while (index <= 126404) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[126406] = true;
    instance.array[126409] = true;
    index = 126411;
    while (index <= 126420) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126422;
    while (index <= 126425) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[126427] = true;
    instance.array[126429] = true;
    instance.array[126436] = true;
    instance.array[126441] = true;
    instance.array[126443] = true;
    instance.array[126445] = true;
    index = 126447;
    while (index <= 126449) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126451;
    while (index <= 126452) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[126454] = true;
    instance.array[126457] = true;
    instance.array[126459] = true;
    instance.array[126461] = true;
    instance.array[126463] = true;
    instance.array[126465] = true;
    index = 126467;
    while (index <= 126468) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[126470] = true;
    index = 126473;
    while (index <= 126476) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126478;
    while (index <= 126484) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126486;
    while (index <= 126489) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126491;
    while (index <= 126494) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[126496] = true;
    index = 126498;
    while (index <= 126507) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126509;
    while (index <= 126525) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126531;
    while (index <= 126533) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126535;
    while (index <= 126539) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126541;
    while (index <= 126557) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *OtherMath) void {
    self.allocator.free(self.array);
}

// isOtherMath checks if cp is of the kind Other_Math.
pub fn isOtherMath(self: OtherMath, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
