// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Other_Alphabetic code points.

const std = @import("std");
const mem = std.mem;

const OtherAlphabetic = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 837,
hi: u21 = 127369,

pub fn init(allocator: *mem.Allocator) !OtherAlphabetic {
    var instance = OtherAlphabetic{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 126533),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    instance.array[0] = true;
    index = 619;
    while (index <= 632) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[634] = true;
    index = 636;
    while (index <= 637) : (index += 1) {
        instance.array[index] = true;
    }
    index = 639;
    while (index <= 640) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[642] = true;
    index = 715;
    while (index <= 725) : (index += 1) {
        instance.array[index] = true;
    }
    index = 774;
    while (index <= 786) : (index += 1) {
        instance.array[index] = true;
    }
    index = 788;
    while (index <= 794) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[811] = true;
    index = 913;
    while (index <= 919) : (index += 1) {
        instance.array[index] = true;
    }
    index = 924;
    while (index <= 927) : (index += 1) {
        instance.array[index] = true;
    }
    index = 930;
    while (index <= 931) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[936] = true;
    instance.array[972] = true;
    index = 1003;
    while (index <= 1018) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1121;
    while (index <= 1131) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1233;
    while (index <= 1234) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1238;
    while (index <= 1246) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1248;
    while (index <= 1250) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1252;
    while (index <= 1255) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1423;
    while (index <= 1434) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1438;
    while (index <= 1444) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1451;
    while (index <= 1469) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1470] = true;
    instance.array[1525] = true;
    instance.array[1526] = true;
    index = 1529;
    while (index <= 1531) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1532;
    while (index <= 1539) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1540;
    while (index <= 1543) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1545;
    while (index <= 1546) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1552;
    while (index <= 1554) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1565;
    while (index <= 1566) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1596] = true;
    index = 1597;
    while (index <= 1598) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1657;
    while (index <= 1659) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1660;
    while (index <= 1663) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1666;
    while (index <= 1667) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1670;
    while (index <= 1671) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1682] = true;
    index = 1693;
    while (index <= 1694) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1724;
    while (index <= 1725) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1726] = true;
    index = 1785;
    while (index <= 1787) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1788;
    while (index <= 1789) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1794;
    while (index <= 1795) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1798;
    while (index <= 1799) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1804] = true;
    index = 1835;
    while (index <= 1836) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1840] = true;
    index = 1852;
    while (index <= 1853) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1854] = true;
    index = 1913;
    while (index <= 1915) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1916;
    while (index <= 1920) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1922;
    while (index <= 1923) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1924] = true;
    index = 1926;
    while (index <= 1927) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1949;
    while (index <= 1950) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1973;
    while (index <= 1975) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1980] = true;
    index = 1981;
    while (index <= 1982) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2041] = true;
    instance.array[2042] = true;
    instance.array[2043] = true;
    index = 2044;
    while (index <= 2047) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2050;
    while (index <= 2051) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2054;
    while (index <= 2055) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2065] = true;
    instance.array[2066] = true;
    index = 2077;
    while (index <= 2078) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2109] = true;
    index = 2169;
    while (index <= 2170) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2171] = true;
    index = 2172;
    while (index <= 2173) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2177;
    while (index <= 2179) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2181;
    while (index <= 2183) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2194] = true;
    instance.array[2235] = true;
    index = 2236;
    while (index <= 2238) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2297;
    while (index <= 2299) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2300;
    while (index <= 2303) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2305;
    while (index <= 2307) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2309;
    while (index <= 2311) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2320;
    while (index <= 2321) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2333;
    while (index <= 2334) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2364] = true;
    index = 2365;
    while (index <= 2366) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2425] = true;
    instance.array[2426] = true;
    index = 2427;
    while (index <= 2431) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2433] = true;
    index = 2434;
    while (index <= 2435) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2437;
    while (index <= 2438) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2439] = true;
    index = 2448;
    while (index <= 2449) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2461;
    while (index <= 2462) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2491;
    while (index <= 2492) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2493;
    while (index <= 2494) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2553;
    while (index <= 2555) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2556;
    while (index <= 2559) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2561;
    while (index <= 2563) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2565;
    while (index <= 2567) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2578] = true;
    index = 2589;
    while (index <= 2590) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2620] = true;
    index = 2621;
    while (index <= 2622) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2698;
    while (index <= 2700) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2701;
    while (index <= 2703) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2705] = true;
    index = 2707;
    while (index <= 2714) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2733;
    while (index <= 2734) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2796] = true;
    index = 2799;
    while (index <= 2805) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2824] = true;
    instance.array[2924] = true;
    index = 2927;
    while (index <= 2932) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2934;
    while (index <= 2935) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2952] = true;
    index = 3116;
    while (index <= 3129) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3130] = true;
    index = 3131;
    while (index <= 3132) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3144;
    while (index <= 3154) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3156;
    while (index <= 3191) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3302;
    while (index <= 3303) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3304;
    while (index <= 3307) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3308] = true;
    index = 3309;
    while (index <= 3313) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3315] = true;
    index = 3318;
    while (index <= 3319) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3320;
    while (index <= 3321) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3345;
    while (index <= 3346) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3347;
    while (index <= 3348) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3353;
    while (index <= 3355) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3357;
    while (index <= 3359) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3362;
    while (index <= 3368) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3372;
    while (index <= 3375) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3389] = true;
    index = 3390;
    while (index <= 3391) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3392;
    while (index <= 3393) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3394;
    while (index <= 3399) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3400] = true;
    instance.array[3402] = true;
    index = 3413;
    while (index <= 3415) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3416] = true;
    index = 5069;
    while (index <= 5070) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5101;
    while (index <= 5102) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5133;
    while (index <= 5134) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5165;
    while (index <= 5166) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[5233] = true;
    index = 5234;
    while (index <= 5240) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5241;
    while (index <= 5248) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[5249] = true;
    index = 5250;
    while (index <= 5251) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5440;
    while (index <= 5441) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[5476] = true;
    index = 5595;
    while (index <= 5597) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5598;
    while (index <= 5601) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5602;
    while (index <= 5603) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5604;
    while (index <= 5606) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5611;
    while (index <= 5612) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[5613] = true;
    index = 5614;
    while (index <= 5619) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5842;
    while (index <= 5843) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5844;
    while (index <= 5845) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[5846] = true;
    instance.array[5904] = true;
    instance.array[5905] = true;
    instance.array[5906] = true;
    index = 5907;
    while (index <= 5913) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[5916] = true;
    instance.array[5917] = true;
    index = 5918;
    while (index <= 5919) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5920;
    while (index <= 5927) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5928;
    while (index <= 5933) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5934;
    while (index <= 5935) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6010;
    while (index <= 6011) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6075;
    while (index <= 6078) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6079] = true;
    instance.array[6128] = true;
    index = 6129;
    while (index <= 6133) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6134] = true;
    instance.array[6135] = true;
    index = 6136;
    while (index <= 6140) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6141] = true;
    instance.array[6142] = true;
    index = 6203;
    while (index <= 6204) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6205] = true;
    instance.array[6236] = true;
    index = 6237;
    while (index <= 6240) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6241;
    while (index <= 6242) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6243;
    while (index <= 6244) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6247;
    while (index <= 6248) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6306] = true;
    index = 6307;
    while (index <= 6308) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6309;
    while (index <= 6311) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6312] = true;
    instance.array[6313] = true;
    index = 6314;
    while (index <= 6316) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6367;
    while (index <= 6374) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6375;
    while (index <= 6382) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6383;
    while (index <= 6384) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6385] = true;
    index = 6818;
    while (index <= 6831) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8561;
    while (index <= 8612) : (index += 1) {
        instance.array[index] = true;
    }
    index = 10907;
    while (index <= 10938) : (index += 1) {
        instance.array[index] = true;
    }
    index = 41775;
    while (index <= 41782) : (index += 1) {
        instance.array[index] = true;
    }
    index = 41817;
    while (index <= 41818) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42173] = true;
    instance.array[42182] = true;
    index = 42206;
    while (index <= 42207) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42208;
    while (index <= 42209) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42210] = true;
    index = 42299;
    while (index <= 42300) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42351;
    while (index <= 42366) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42368] = true;
    instance.array[42426] = true;
    index = 42465;
    while (index <= 42469) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42498;
    while (index <= 42508) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42509] = true;
    index = 42555;
    while (index <= 42557) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42558] = true;
    index = 42607;
    while (index <= 42608) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42609;
    while (index <= 42612) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42613;
    while (index <= 42614) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42615;
    while (index <= 42616) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42617;
    while (index <= 42618) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42656] = true;
    index = 42724;
    while (index <= 42729) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42730;
    while (index <= 42731) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42732;
    while (index <= 42733) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42734;
    while (index <= 42735) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42736;
    while (index <= 42737) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42750] = true;
    instance.array[42759] = true;
    instance.array[42760] = true;
    instance.array[42806] = true;
    instance.array[42807] = true;
    instance.array[42808] = true;
    instance.array[42859] = true;
    index = 42861;
    while (index <= 42863) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42866;
    while (index <= 42867) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42873] = true;
    instance.array[42918] = true;
    index = 42919;
    while (index <= 42920) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42921;
    while (index <= 42922) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42928] = true;
    index = 43166;
    while (index <= 43167) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43168] = true;
    index = 43169;
    while (index <= 43170) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43171] = true;
    index = 43172;
    while (index <= 43173) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[63449] = true;
    index = 65585;
    while (index <= 65589) : (index += 1) {
        instance.array[index] = true;
    }
    index = 67260;
    while (index <= 67262) : (index += 1) {
        instance.array[index] = true;
    }
    index = 67264;
    while (index <= 67265) : (index += 1) {
        instance.array[index] = true;
    }
    index = 67271;
    while (index <= 67274) : (index += 1) {
        instance.array[index] = true;
    }
    index = 68063;
    while (index <= 68066) : (index += 1) {
        instance.array[index] = true;
    }
    index = 68454;
    while (index <= 68455) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[68795] = true;
    instance.array[68796] = true;
    instance.array[68797] = true;
    index = 68851;
    while (index <= 68864) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[68925] = true;
    index = 68971;
    while (index <= 68973) : (index += 1) {
        instance.array[index] = true;
    }
    index = 68974;
    while (index <= 68977) : (index += 1) {
        instance.array[index] = true;
    }
    index = 68978;
    while (index <= 68979) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69051;
    while (index <= 69053) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69090;
    while (index <= 69094) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[69095] = true;
    index = 69096;
    while (index <= 69101) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69120;
    while (index <= 69121) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69179;
    while (index <= 69180) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[69181] = true;
    index = 69230;
    while (index <= 69232) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69233;
    while (index <= 69241) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[69242] = true;
    instance.array[69257] = true;
    instance.array[69258] = true;
    index = 69351;
    while (index <= 69353) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69354;
    while (index <= 69356) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69357;
    while (index <= 69358) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[69359] = true;
    instance.array[69362] = true;
    instance.array[69369] = true;
    instance.array[69530] = true;
    index = 69531;
    while (index <= 69533) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69534;
    while (index <= 69539) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69563;
    while (index <= 69564) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69565;
    while (index <= 69566) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69625;
    while (index <= 69626) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[69627] = true;
    index = 69628;
    while (index <= 69631) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69634;
    while (index <= 69635) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69638;
    while (index <= 69639) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[69650] = true;
    index = 69661;
    while (index <= 69662) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69872;
    while (index <= 69874) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69875;
    while (index <= 69882) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69883;
    while (index <= 69884) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69886;
    while (index <= 69887) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[69888] = true;
    index = 69995;
    while (index <= 69997) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69998;
    while (index <= 70003) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70004] = true;
    instance.array[70005] = true;
    index = 70006;
    while (index <= 70009) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70010;
    while (index <= 70011) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70012] = true;
    index = 70250;
    while (index <= 70252) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70253;
    while (index <= 70256) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70259;
    while (index <= 70262) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70263;
    while (index <= 70264) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70265] = true;
    index = 70295;
    while (index <= 70296) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70379;
    while (index <= 70381) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70382;
    while (index <= 70389) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70390;
    while (index <= 70391) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70392] = true;
    instance.array[70393] = true;
    instance.array[70395] = true;
    instance.array[70502] = true;
    instance.array[70503] = true;
    instance.array[70504] = true;
    index = 70505;
    while (index <= 70506) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70507;
    while (index <= 70512) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70616;
    while (index <= 70618) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70619;
    while (index <= 70620) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70621;
    while (index <= 70624) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70625] = true;
    index = 70626;
    while (index <= 70629) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70887;
    while (index <= 70889) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70890;
    while (index <= 70898) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70899] = true;
    index = 71147;
    while (index <= 71152) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71154;
    while (index <= 71155) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71158;
    while (index <= 71159) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[71163] = true;
    instance.array[71165] = true;
    index = 71308;
    while (index <= 71310) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71311;
    while (index <= 71314) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71317;
    while (index <= 71318) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71319;
    while (index <= 71322) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[71327] = true;
    index = 71356;
    while (index <= 71365) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71408;
    while (index <= 71411) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[71412] = true;
    index = 71414;
    while (index <= 71417) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71436;
    while (index <= 71441) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71442;
    while (index <= 71443) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71444;
    while (index <= 71446) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71493;
    while (index <= 71505) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[71506] = true;
    instance.array[71914] = true;
    index = 71915;
    while (index <= 71921) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71923;
    while (index <= 71928) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[71929] = true;
    index = 72013;
    while (index <= 72034) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[72036] = true;
    index = 72037;
    while (index <= 72043) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[72044] = true;
    index = 72045;
    while (index <= 72046) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[72047] = true;
    index = 72048;
    while (index <= 72049) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72172;
    while (index <= 72177) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[72181] = true;
    index = 72183;
    while (index <= 72184) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72186;
    while (index <= 72188) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[72190] = true;
    instance.array[72194] = true;
    index = 72261;
    while (index <= 72265) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72267;
    while (index <= 72268) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72270;
    while (index <= 72271) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[72272] = true;
    instance.array[72273] = true;
    index = 72622;
    while (index <= 72623) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72624;
    while (index <= 72625) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[93194] = true;
    index = 93196;
    while (index <= 93250) : (index += 1) {
        instance.array[index] = true;
    }
    index = 93258;
    while (index <= 93261) : (index += 1) {
        instance.array[index] = true;
    }
    index = 93355;
    while (index <= 93356) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[112985] = true;
    index = 122043;
    while (index <= 122049) : (index += 1) {
        instance.array[index] = true;
    }
    index = 122051;
    while (index <= 122067) : (index += 1) {
        instance.array[index] = true;
    }
    index = 122070;
    while (index <= 122076) : (index += 1) {
        instance.array[index] = true;
    }
    index = 122078;
    while (index <= 122079) : (index += 1) {
        instance.array[index] = true;
    }
    index = 122081;
    while (index <= 122085) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[124418] = true;
    index = 126443;
    while (index <= 126468) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126475;
    while (index <= 126500) : (index += 1) {
        instance.array[index] = true;
    }
    index = 126507;
    while (index <= 126532) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *OtherAlphabetic) void {
    self.allocator.free(self.array);
}

// isOtherAlphabetic checks if cp is of the kind Other_Alphabetic.
pub fn isOtherAlphabetic(self: OtherAlphabetic, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
