// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Other_Default_Ignorable_Code_Point code points.

const std = @import("std");
const mem = std.mem;

const OtherDefaultIgnorableCodePoint = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 329,
hi: u21 = 921599,

pub fn init(allocator: *mem.Allocator) !OtherDefaultIgnorableCodePoint {
    var instance = OtherDefaultIgnorableCodePoint{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 921271),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    instance.array[518] = true;
    index = 4118;
    while (index <= 4119) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5739;
    while (index <= 5740) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[7964] = true;
    instance.array[12315] = true;
    instance.array[65111] = true;
    index = 65191;
    while (index <= 65199) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[917175] = true;
    index = 917177;
    while (index <= 917206) : (index += 1) {
        instance.array[index] = true;
    }
    index = 917303;
    while (index <= 917430) : (index += 1) {
        instance.array[index] = true;
    }
    index = 917671;
    while (index <= 921270) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *OtherDefaultIgnorableCodePoint) void {
    self.allocator.free(self.array);
}

// isOtherDefaultIgnorableCodePoint checks if cp is of the kind Other_Default_Ignorable_Code_Point.
pub fn isOtherDefaultIgnorableCodePoint(self: OtherDefaultIgnorableCodePoint, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
