// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Sentence_Terminal code points.

const std = @import("std");
const mem = std.mem;

const SentenceTerminal = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 46,
hi: u21 = 121480,

pub fn init(allocator: *mem.Allocator) !SentenceTerminal {
    var instance = SentenceTerminal{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 121435),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    instance.array[2097139] = true;
    instance.array[0] = true;
    instance.array[17] = true;
    instance.array[1371] = true;
    index = 1520;
    while (index <= 1521) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1702] = true;
    index = 1746;
    while (index <= 1748) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1995] = true;
    instance.array[2057] = true;
    instance.array[2059] = true;
    index = 2063;
    while (index <= 2064) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2358;
    while (index <= 2359) : (index += 1) {
        instance.array[index] = true;
    }
    index = 4124;
    while (index <= 4125) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[4916] = true;
    index = 4921;
    while (index <= 4922) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[5696] = true;
    index = 5895;
    while (index <= 5896) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6101] = true;
    instance.array[6107] = true;
    index = 6422;
    while (index <= 6423) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6778;
    while (index <= 6781) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6956;
    while (index <= 6957) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6960;
    while (index <= 6961) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7181;
    while (index <= 7182) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7248;
    while (index <= 7249) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8206;
    while (index <= 8207) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8217;
    while (index <= 8219) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[11776] = true;
    instance.array[11790] = true;
    instance.array[12244] = true;
    instance.array[42193] = true;
    index = 42464;
    while (index <= 42465) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42693] = true;
    instance.array[42697] = true;
    index = 43080;
    while (index <= 43081) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43168;
    while (index <= 43169) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43265] = true;
    index = 43418;
    while (index <= 43419) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43567;
    while (index <= 43569) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43714;
    while (index <= 43715) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43965] = true;
    instance.array[65060] = true;
    index = 65064;
    while (index <= 65065) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[65235] = true;
    instance.array[65248] = true;
    instance.array[65265] = true;
    instance.array[65331] = true;
    index = 68136;
    while (index <= 68137) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69415;
    while (index <= 69419) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69657;
    while (index <= 69658) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69776;
    while (index <= 69779) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69907;
    while (index <= 69909) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70039;
    while (index <= 70040) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70047] = true;
    index = 70064;
    while (index <= 70065) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70154;
    while (index <= 70155) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70157;
    while (index <= 70158) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70267] = true;
    index = 70685;
    while (index <= 70686) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71060;
    while (index <= 71061) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71067;
    while (index <= 71081) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71187;
    while (index <= 71188) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71438;
    while (index <= 71440) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[71958] = true;
    instance.array[71960] = true;
    index = 72212;
    while (index <= 72213) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72301;
    while (index <= 72302) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72723;
    while (index <= 72724) : (index += 1) {
        instance.array[index] = true;
    }
    index = 73417;
    while (index <= 73418) : (index += 1) {
        instance.array[index] = true;
    }
    index = 92736;
    while (index <= 92737) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[92871] = true;
    index = 92937;
    while (index <= 92938) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[92950] = true;
    instance.array[93802] = true;
    instance.array[113777] = true;
    instance.array[121434] = true;

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *SentenceTerminal) void {
    self.allocator.free(self.array);
}

// isSentenceTerminal checks if cp is of the kind Sentence_Terminal.
pub fn isSentenceTerminal(self: SentenceTerminal, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
