// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Lowest code point
//    3. Highest code point
//! Unicode Enclosing_Mark code points.

const std = @import("std");
const mem = std.mem;

const EnclosingMark = @This();

allocator: *mem.Allocator,
cp_set: std.AutoHashMap(u21, void),
lo: u21 = 1160,
hi: u21 = 42610,

const Singleton = struct {
    instance: *EnclosingMark,
    ref_count: usize,
};

var singleton: ?Singleton = null;

pub fn init(allocator: *mem.Allocator) !*EnclosingMark {
    if (singleton) |*s| {
        s.ref_count += 1;
        return s.instance;
    }

    var instance = try allocator.create(EnclosingMark);

    instance.* = EnclosingMark{
        .allocator = allocator,
        .cp_set = std.AutoHashMap(u21, void).init(allocator),
    };

    var index: u21 = 0;
    index = 1160;
    while (index <= 1161) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(6846, {});
    index = 8413;
    while (index <= 8416) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 8418;
    while (index <= 8420) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 42608;
    while (index <= 42610) : (index += 1) {
        try instance.cp_set.put(index, {});
    }

    // Placeholder: 0. Struct name, 1. Code point kind
    singleton = Singleton{
        .instance = instance,
        .ref_count = 1,
    };

    return instance;
}

pub fn deinit(self: *EnclosingMark) void {
    self.cp_set.deinit();
    if (singleton) |*s| {
        s.ref_count -= 1;
        if (s.ref_count == 0) {
            self.allocator.destroy(s.instance);
            singleton = null;
        }
    }
}

// isEnclosingMark checks if cp is of the kind Enclosing_Mark.
pub fn isEnclosingMark(self: EnclosingMark, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    return self.cp_set.get(cp) != null;
}
