// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Lowest code point
//    3. Highest code point
//! Unicode Final_Punctuation code points.

const std = @import("std");
const mem = std.mem;

const FinalPunctuation = @This();

allocator: *mem.Allocator,
cp_set: std.AutoHashMap(u21, void),
lo: u21 = 187,
hi: u21 = 11809,

pub fn init(allocator: *mem.Allocator) !FinalPunctuation {
    var instance = FinalPunctuation{
        .allocator = allocator,
        .cp_set = std.AutoHashMap(u21, void).init(allocator),
    };

    var index: u21 = 0;
    try instance.cp_set.put(187, {});
    try instance.cp_set.put(8217, {});
    try instance.cp_set.put(8221, {});
    try instance.cp_set.put(8250, {});
    try instance.cp_set.put(11779, {});
    try instance.cp_set.put(11781, {});
    try instance.cp_set.put(11786, {});
    try instance.cp_set.put(11789, {});
    try instance.cp_set.put(11805, {});
    try instance.cp_set.put(11809, {});

    // Placeholder: 0. Struct name, 1. Code point kind
    return instance;
}

pub fn deinit(self: *FinalPunctuation) void {
    self.cp_set.deinit();
}

// isFinalPunctuation checks if cp is of the kind Final_Punctuation.
pub fn isFinalPunctuation(self: FinalPunctuation, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    return self.cp_set.get(cp) != null;
}
