// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Format code points.

lo: u21 = 173,
hi: u21 = 917631,

const Format = @This();

pub fn isFormat(self: Format, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    return switch (cp) {
        0xad => true,
        0x600...0x605 => true,
        0x61c => true,
        0x6dd => true,
        0x70f => true,
        0x8e2 => true,
        0x180e => true,
        0x200b...0x200f => true,
        0x202a...0x202e => true,
        0x2060...0x2064 => true,
        0x2066...0x206f => true,
        0xfeff => true,
        0xfff9...0xfffb => true,
        0x110bd => true,
        0x110cd => true,
        0x13430...0x13438 => true,
        0x1bca0...0x1bca3 => true,
        0x1d173...0x1d17a => true,
        0xe0001 => true,
        0xe0020...0xe007f => true,
        else => false,
    };
}