// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Lowest code point
//    3. Highest code point
//! Unicode Other_Number code points.

const std = @import("std");
const mem = std.mem;

const OtherNumber = @This();

allocator: *mem.Allocator,
cp_set: std.AutoHashMap(u21, void),
lo: u21 = 178,
hi: u21 = 127244,

const Singleton = struct {
    instance: *OtherNumber,
    ref_count: usize,
};

var singleton: ?Singleton = null;

pub fn init(allocator: *mem.Allocator) !*OtherNumber {
    if (singleton) |*s| {
        s.ref_count += 1;
        return s.instance;
    }

    var instance = try allocator.create(OtherNumber);

    instance.* = OtherNumber{
        .allocator = allocator,
        .cp_set = std.AutoHashMap(u21, void).init(allocator),
    };

    var index: u21 = 0;
    index = 178;
    while (index <= 179) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(185, {});
    index = 188;
    while (index <= 190) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 2548;
    while (index <= 2553) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 2930;
    while (index <= 2935) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 3056;
    while (index <= 3058) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 3192;
    while (index <= 3198) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 3416;
    while (index <= 3422) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 3440;
    while (index <= 3448) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 3882;
    while (index <= 3891) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 4969;
    while (index <= 4988) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 6128;
    while (index <= 6137) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(6618, {});
    try instance.cp_set.put(8304, {});
    index = 8308;
    while (index <= 8313) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 8320;
    while (index <= 8329) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 8528;
    while (index <= 8543) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(8585, {});
    index = 9312;
    while (index <= 9371) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 9450;
    while (index <= 9471) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 10102;
    while (index <= 10131) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(11517, {});
    index = 12690;
    while (index <= 12693) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 12832;
    while (index <= 12841) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 12872;
    while (index <= 12879) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 12881;
    while (index <= 12895) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 12928;
    while (index <= 12937) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 12977;
    while (index <= 12991) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 43056;
    while (index <= 43061) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 65799;
    while (index <= 65843) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 65909;
    while (index <= 65912) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 65930;
    while (index <= 65931) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 66273;
    while (index <= 66299) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 66336;
    while (index <= 66339) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 67672;
    while (index <= 67679) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 67705;
    while (index <= 67711) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 67751;
    while (index <= 67759) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 67835;
    while (index <= 67839) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 67862;
    while (index <= 67867) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68028;
    while (index <= 68029) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68032;
    while (index <= 68047) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68050;
    while (index <= 68095) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68160;
    while (index <= 68168) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68221;
    while (index <= 68222) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68253;
    while (index <= 68255) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68331;
    while (index <= 68335) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68440;
    while (index <= 68447) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68472;
    while (index <= 68479) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68521;
    while (index <= 68527) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68858;
    while (index <= 68863) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 69216;
    while (index <= 69246) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 69405;
    while (index <= 69414) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 69457;
    while (index <= 69460) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 69573;
    while (index <= 69579) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 69714;
    while (index <= 69733) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 70113;
    while (index <= 70132) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 71482;
    while (index <= 71483) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 71914;
    while (index <= 71922) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 72794;
    while (index <= 72812) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 73664;
    while (index <= 73684) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 93019;
    while (index <= 93025) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 93824;
    while (index <= 93846) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 119520;
    while (index <= 119539) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 119648;
    while (index <= 119672) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 125127;
    while (index <= 125135) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 126065;
    while (index <= 126123) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 126125;
    while (index <= 126127) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 126129;
    while (index <= 126132) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 126209;
    while (index <= 126253) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 126255;
    while (index <= 126269) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 127232;
    while (index <= 127244) : (index += 1) {
        try instance.cp_set.put(index, {});
    }

    // Placeholder: 0. Struct name, 1. Code point kind
    singleton = Singleton{
        .instance = instance,
        .ref_count = 1,
    };

    return instance;
}

pub fn deinit(self: *OtherNumber) void {
    if (singleton) |*s| {
        s.ref_count -= 1;
        if (s.ref_count == 0) {
            self.cp_set.deinit();
            self.allocator.destroy(s.instance);
            singleton = null;
        }
    }
}

// isOtherNumber checks if cp is of the kind Other_Number.
pub fn isOtherNumber(self: OtherNumber, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    return self.cp_set.get(cp) != null;
}
