// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Case_Ignorable code points.

const std = @import("std");
const mem = std.mem;

const CaseIgnorable = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 46,
hi: u21 = 917999,

pub fn init(allocator: *mem.Allocator) !CaseIgnorable {
    var instance = CaseIgnorable{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 917954),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    instance.array[2097145] = true;
    instance.array[0] = true;
    instance.array[12] = true;
    instance.array[48] = true;
    instance.array[50] = true;
    instance.array[122] = true;
    instance.array[127] = true;
    instance.array[129] = true;
    instance.array[134] = true;
    instance.array[137] = true;
    instance.array[138] = true;
    index = 642;
    while (index <= 659) : (index += 1) {
        instance.array[index] = true;
    }
    index = 660;
    while (index <= 663) : (index += 1) {
        instance.array[index] = true;
    }
    index = 664;
    while (index <= 675) : (index += 1) {
        instance.array[index] = true;
    }
    index = 676;
    while (index <= 689) : (index += 1) {
        instance.array[index] = true;
    }
    index = 690;
    while (index <= 694) : (index += 1) {
        instance.array[index] = true;
    }
    index = 695;
    while (index <= 701) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[702] = true;
    instance.array[703] = true;
    instance.array[704] = true;
    index = 705;
    while (index <= 721) : (index += 1) {
        instance.array[index] = true;
    }
    index = 722;
    while (index <= 833) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[838] = true;
    instance.array[839] = true;
    instance.array[844] = true;
    index = 854;
    while (index <= 855) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[857] = true;
    index = 1109;
    while (index <= 1113) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1114;
    while (index <= 1115) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1323] = true;
    instance.array[1329] = true;
    index = 1379;
    while (index <= 1423) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1425] = true;
    index = 1427;
    while (index <= 1428) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1430;
    while (index <= 1431) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1433] = true;
    instance.array[1478] = true;
    index = 1490;
    while (index <= 1495) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1506;
    while (index <= 1516) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1518] = true;
    instance.array[1554] = true;
    index = 1565;
    while (index <= 1585) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1602] = true;
    index = 1704;
    while (index <= 1710) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1711] = true;
    index = 1713;
    while (index <= 1718) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1719;
    while (index <= 1720) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1721;
    while (index <= 1722) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1724;
    while (index <= 1727) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1761] = true;
    instance.array[1763] = true;
    index = 1794;
    while (index <= 1820) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1912;
    while (index <= 1922) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1981;
    while (index <= 1989) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1990;
    while (index <= 1991) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[1996] = true;
    instance.array[1999] = true;
    index = 2024;
    while (index <= 2027) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2028] = true;
    index = 2029;
    while (index <= 2037) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2038] = true;
    index = 2039;
    while (index <= 2041) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2042] = true;
    index = 2043;
    while (index <= 2047) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2091;
    while (index <= 2093) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2213;
    while (index <= 2227) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2228] = true;
    index = 2229;
    while (index <= 2260) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2316] = true;
    instance.array[2318] = true;
    index = 2323;
    while (index <= 2330) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2335] = true;
    index = 2339;
    while (index <= 2345) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2356;
    while (index <= 2357) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2371] = true;
    instance.array[2387] = true;
    instance.array[2446] = true;
    index = 2451;
    while (index <= 2454) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2463] = true;
    index = 2484;
    while (index <= 2485) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2512] = true;
    index = 2515;
    while (index <= 2516) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2574] = true;
    index = 2579;
    while (index <= 2580) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2585;
    while (index <= 2586) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2589;
    while (index <= 2591) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2595] = true;
    index = 2626;
    while (index <= 2627) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2631] = true;
    index = 2643;
    while (index <= 2644) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2702] = true;
    index = 2707;
    while (index <= 2711) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2713;
    while (index <= 2714) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2719] = true;
    index = 2740;
    while (index <= 2741) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2764;
    while (index <= 2769) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2771] = true;
    instance.array[2830] = true;
    instance.array[2833] = true;
    index = 2835;
    while (index <= 2838) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2847] = true;
    index = 2855;
    while (index <= 2856) : (index += 1) {
        instance.array[index] = true;
    }
    index = 2868;
    while (index <= 2869) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[2900] = true;
    instance.array[2962] = true;
    instance.array[2975] = true;
    instance.array[3026] = true;
    instance.array[3030] = true;
    index = 3088;
    while (index <= 3090) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3096;
    while (index <= 3098) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3100;
    while (index <= 3103) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3111;
    while (index <= 3112) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3124;
    while (index <= 3125) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3155] = true;
    instance.array[3214] = true;
    instance.array[3217] = true;
    instance.array[3224] = true;
    index = 3230;
    while (index <= 3231) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3252;
    while (index <= 3253) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3282;
    while (index <= 3283) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3341;
    while (index <= 3342) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3347;
    while (index <= 3350) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3359] = true;
    index = 3380;
    while (index <= 3381) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3411] = true;
    instance.array[3484] = true;
    index = 3492;
    while (index <= 3494) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3496] = true;
    instance.array[3587] = true;
    index = 3590;
    while (index <= 3596) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3608] = true;
    index = 3609;
    while (index <= 3616) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3715] = true;
    index = 3718;
    while (index <= 3726) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3736] = true;
    index = 3738;
    while (index <= 3743) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3818;
    while (index <= 3819) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3847] = true;
    instance.array[3849] = true;
    instance.array[3851] = true;
    index = 3907;
    while (index <= 3920) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3922;
    while (index <= 3926) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3928;
    while (index <= 3929) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3935;
    while (index <= 3945) : (index += 1) {
        instance.array[index] = true;
    }
    index = 3947;
    while (index <= 3982) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[3992] = true;
    index = 4095;
    while (index <= 4098) : (index += 1) {
        instance.array[index] = true;
    }
    index = 4100;
    while (index <= 4105) : (index += 1) {
        instance.array[index] = true;
    }
    index = 4107;
    while (index <= 4108) : (index += 1) {
        instance.array[index] = true;
    }
    index = 4111;
    while (index <= 4112) : (index += 1) {
        instance.array[index] = true;
    }
    index = 4138;
    while (index <= 4139) : (index += 1) {
        instance.array[index] = true;
    }
    index = 4144;
    while (index <= 4146) : (index += 1) {
        instance.array[index] = true;
    }
    index = 4163;
    while (index <= 4166) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[4180] = true;
    index = 4183;
    while (index <= 4184) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[4191] = true;
    instance.array[4207] = true;
    instance.array[4302] = true;
    index = 4911;
    while (index <= 4913) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5860;
    while (index <= 5862) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5892;
    while (index <= 5894) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5924;
    while (index <= 5925) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5956;
    while (index <= 5957) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6022;
    while (index <= 6023) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6025;
    while (index <= 6031) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6040] = true;
    index = 6043;
    while (index <= 6053) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6057] = true;
    instance.array[6063] = true;
    index = 6109;
    while (index <= 6111) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6112] = true;
    instance.array[6165] = true;
    index = 6231;
    while (index <= 6232) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6267] = true;
    index = 6386;
    while (index <= 6388) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6393;
    while (index <= 6394) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6404] = true;
    index = 6411;
    while (index <= 6413) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6633;
    while (index <= 6634) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6637] = true;
    instance.array[6696] = true;
    index = 6698;
    while (index <= 6704) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6706] = true;
    instance.array[6708] = true;
    index = 6711;
    while (index <= 6718) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6725;
    while (index <= 6734) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6737] = true;
    instance.array[6777] = true;
    index = 6786;
    while (index <= 6799) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6800] = true;
    index = 6801;
    while (index <= 6802) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6866;
    while (index <= 6869) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6918] = true;
    index = 6920;
    while (index <= 6924) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[6926] = true;
    instance.array[6932] = true;
    index = 6973;
    while (index <= 6981) : (index += 1) {
        instance.array[index] = true;
    }
    index = 6994;
    while (index <= 6995) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7028;
    while (index <= 7031) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7034;
    while (index <= 7035) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7037;
    while (index <= 7039) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[7096] = true;
    index = 7098;
    while (index <= 7099) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[7103] = true;
    index = 7105;
    while (index <= 7107) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7166;
    while (index <= 7173) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7176;
    while (index <= 7177) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7242;
    while (index <= 7247) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7330;
    while (index <= 7332) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7334;
    while (index <= 7346) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7348;
    while (index <= 7354) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[7359] = true;
    instance.array[7366] = true;
    index = 7370;
    while (index <= 7371) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7422;
    while (index <= 7484) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[7498] = true;
    index = 7533;
    while (index <= 7569) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7570;
    while (index <= 7627) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7629;
    while (index <= 7633) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8079] = true;
    index = 8081;
    while (index <= 8083) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8095;
    while (index <= 8097) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8111;
    while (index <= 8113) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8127;
    while (index <= 8129) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8143;
    while (index <= 8144) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8157;
    while (index <= 8161) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8170] = true;
    instance.array[8171] = true;
    instance.array[8182] = true;
    instance.array[8185] = true;
    index = 8188;
    while (index <= 8192) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8242;
    while (index <= 8246) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8248;
    while (index <= 8257) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8259] = true;
    instance.array[8273] = true;
    index = 8290;
    while (index <= 8302) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8354;
    while (index <= 8366) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8367;
    while (index <= 8370) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8371] = true;
    index = 8372;
    while (index <= 8374) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8375;
    while (index <= 8386) : (index += 1) {
        instance.array[index] = true;
    }
    index = 11342;
    while (index <= 11343) : (index += 1) {
        instance.array[index] = true;
    }
    index = 11457;
    while (index <= 11459) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[11585] = true;
    instance.array[11601] = true;
    index = 11698;
    while (index <= 11729) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[11777] = true;
    instance.array[12247] = true;
    index = 12284;
    while (index <= 12287) : (index += 1) {
        instance.array[index] = true;
    }
    index = 12291;
    while (index <= 12295) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[12301] = true;
    index = 12395;
    while (index <= 12396) : (index += 1) {
        instance.array[index] = true;
    }
    index = 12397;
    while (index <= 12398) : (index += 1) {
        instance.array[index] = true;
    }
    index = 12399;
    while (index <= 12400) : (index += 1) {
        instance.array[index] = true;
    }
    index = 12494;
    while (index <= 12496) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[40935] = true;
    index = 42186;
    while (index <= 42191) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42462] = true;
    instance.array[42561] = true;
    index = 42562;
    while (index <= 42564) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42566;
    while (index <= 42575) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42577] = true;
    index = 42606;
    while (index <= 42607) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42608;
    while (index <= 42609) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42690;
    while (index <= 42691) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42706;
    while (index <= 42728) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42729;
    while (index <= 42737) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42738;
    while (index <= 42739) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42818] = true;
    instance.array[42842] = true;
    index = 42843;
    while (index <= 42844) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42954;
    while (index <= 42955) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42964] = true;
    instance.array[42968] = true;
    instance.array[42973] = true;
    index = 42999;
    while (index <= 43000) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43006] = true;
    index = 43158;
    while (index <= 43159) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43186;
    while (index <= 43203) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43217] = true;
    index = 43256;
    while (index <= 43263) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43289;
    while (index <= 43299) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43346;
    while (index <= 43348) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43397] = true;
    index = 43400;
    while (index <= 43403) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43406;
    while (index <= 43407) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43425] = true;
    instance.array[43447] = true;
    instance.array[43448] = true;
    index = 43515;
    while (index <= 43520) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43523;
    while (index <= 43524) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43527;
    while (index <= 43528) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43541] = true;
    instance.array[43550] = true;
    instance.array[43586] = true;
    instance.array[43598] = true;
    instance.array[43650] = true;
    index = 43652;
    while (index <= 43654) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43657;
    while (index <= 43658) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43664;
    while (index <= 43665) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43667] = true;
    instance.array[43695] = true;
    index = 43710;
    while (index <= 43711) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43717;
    while (index <= 43718) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43720] = true;
    instance.array[43821] = true;
    index = 43822;
    while (index <= 43825) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43835] = true;
    index = 43836;
    while (index <= 43837) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[43959] = true;
    instance.array[43962] = true;
    instance.array[43967] = true;
    instance.array[64240] = true;
    index = 64388;
    while (index <= 64403) : (index += 1) {
        instance.array[index] = true;
    }
    index = 64978;
    while (index <= 64993) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[64997] = true;
    index = 65010;
    while (index <= 65025) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[65060] = true;
    instance.array[65063] = true;
    instance.array[65233] = true;
    instance.array[65241] = true;
    instance.array[65248] = true;
    instance.array[65260] = true;
    instance.array[65296] = true;
    instance.array[65298] = true;
    instance.array[65346] = true;
    index = 65392;
    while (index <= 65393) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[65461] = true;
    index = 65483;
    while (index <= 65485) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[65999] = true;
    instance.array[66226] = true;
    index = 66376;
    while (index <= 66380) : (index += 1) {
        instance.array[index] = true;
    }
    index = 68051;
    while (index <= 68053) : (index += 1) {
        instance.array[index] = true;
    }
    index = 68055;
    while (index <= 68056) : (index += 1) {
        instance.array[index] = true;
    }
    index = 68062;
    while (index <= 68065) : (index += 1) {
        instance.array[index] = true;
    }
    index = 68106;
    while (index <= 68108) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[68113] = true;
    index = 68279;
    while (index <= 68280) : (index += 1) {
        instance.array[index] = true;
    }
    index = 68854;
    while (index <= 68857) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69245;
    while (index <= 69246) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69400;
    while (index <= 69410) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[69587] = true;
    index = 69642;
    while (index <= 69656) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69713;
    while (index <= 69715) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69765;
    while (index <= 69768) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69771;
    while (index <= 69772) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[69775] = true;
    instance.array[69791] = true;
    index = 69842;
    while (index <= 69844) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69881;
    while (index <= 69885) : (index += 1) {
        instance.array[index] = true;
    }
    index = 69887;
    while (index <= 69894) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[69957] = true;
    index = 69970;
    while (index <= 69971) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70024;
    while (index <= 70032) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70043;
    while (index <= 70046) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70049] = true;
    index = 70145;
    while (index <= 70147) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70150] = true;
    index = 70152;
    while (index <= 70153) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70160] = true;
    instance.array[70321] = true;
    index = 70325;
    while (index <= 70332) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70354;
    while (index <= 70355) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70413;
    while (index <= 70414) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70418] = true;
    index = 70456;
    while (index <= 70462) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70466;
    while (index <= 70470) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70666;
    while (index <= 70673) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70676;
    while (index <= 70678) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70680] = true;
    instance.array[70704] = true;
    index = 70789;
    while (index <= 70794) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[70796] = true;
    index = 70801;
    while (index <= 70802) : (index += 1) {
        instance.array[index] = true;
    }
    index = 70804;
    while (index <= 70805) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71044;
    while (index <= 71047) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71054;
    while (index <= 71055) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71057;
    while (index <= 71058) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71086;
    while (index <= 71087) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71173;
    while (index <= 71180) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[71183] = true;
    index = 71185;
    while (index <= 71186) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[71293] = true;
    instance.array[71295] = true;
    index = 71298;
    while (index <= 71303) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[71305] = true;
    index = 71407;
    while (index <= 71409) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71412;
    while (index <= 71415) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71417;
    while (index <= 71421) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71681;
    while (index <= 71689) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71691;
    while (index <= 71692) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71949;
    while (index <= 71950) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[71952] = true;
    instance.array[71957] = true;
    index = 72102;
    while (index <= 72105) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72108;
    while (index <= 72109) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[72114] = true;
    index = 72147;
    while (index <= 72156) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72197;
    while (index <= 72202) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72205;
    while (index <= 72208) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[72217] = true;
    index = 72227;
    while (index <= 72232) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72235;
    while (index <= 72237) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72284;
    while (index <= 72296) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72298;
    while (index <= 72299) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72706;
    while (index <= 72712) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72714;
    while (index <= 72719) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[72721] = true;
    index = 72804;
    while (index <= 72825) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72828;
    while (index <= 72834) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72836;
    while (index <= 72837) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72839;
    while (index <= 72840) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72963;
    while (index <= 72968) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[72972] = true;
    index = 72974;
    while (index <= 72975) : (index += 1) {
        instance.array[index] = true;
    }
    index = 72977;
    while (index <= 72983) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[72985] = true;
    index = 73058;
    while (index <= 73059) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[73063] = true;
    instance.array[73065] = true;
    index = 73413;
    while (index <= 73414) : (index += 1) {
        instance.array[index] = true;
    }
    index = 78850;
    while (index <= 78858) : (index += 1) {
        instance.array[index] = true;
    }
    index = 92866;
    while (index <= 92870) : (index += 1) {
        instance.array[index] = true;
    }
    index = 92930;
    while (index <= 92936) : (index += 1) {
        instance.array[index] = true;
    }
    index = 92946;
    while (index <= 92949) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[93985] = true;
    index = 94049;
    while (index <= 94052) : (index += 1) {
        instance.array[index] = true;
    }
    index = 94053;
    while (index <= 94065) : (index += 1) {
        instance.array[index] = true;
    }
    index = 94130;
    while (index <= 94131) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[94133] = true;
    instance.array[94134] = true;
    index = 113775;
    while (index <= 113776) : (index += 1) {
        instance.array[index] = true;
    }
    index = 113778;
    while (index <= 113781) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119097;
    while (index <= 119099) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119109;
    while (index <= 119116) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119117;
    while (index <= 119124) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119127;
    while (index <= 119133) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119164;
    while (index <= 119167) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119316;
    while (index <= 119318) : (index += 1) {
        instance.array[index] = true;
    }
    index = 121298;
    while (index <= 121352) : (index += 1) {
        instance.array[index] = true;
    }
    index = 121357;
    while (index <= 121406) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[121415] = true;
    instance.array[121430] = true;
    index = 121453;
    while (index <= 121457) : (index += 1) {
        instance.array[index] = true;
    }
    index = 121459;
    while (index <= 121473) : (index += 1) {
        instance.array[index] = true;
    }
    index = 122834;
    while (index <= 122840) : (index += 1) {
        instance.array[index] = true;
    }
    index = 122842;
    while (index <= 122858) : (index += 1) {
        instance.array[index] = true;
    }
    index = 122861;
    while (index <= 122867) : (index += 1) {
        instance.array[index] = true;
    }
    index = 122869;
    while (index <= 122870) : (index += 1) {
        instance.array[index] = true;
    }
    index = 122872;
    while (index <= 122876) : (index += 1) {
        instance.array[index] = true;
    }
    index = 123138;
    while (index <= 123144) : (index += 1) {
        instance.array[index] = true;
    }
    index = 123145;
    while (index <= 123151) : (index += 1) {
        instance.array[index] = true;
    }
    index = 123582;
    while (index <= 123585) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125090;
    while (index <= 125096) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125206;
    while (index <= 125212) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[125213] = true;
    index = 127949;
    while (index <= 127953) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[917459] = true;
    index = 917490;
    while (index <= 917585) : (index += 1) {
        instance.array[index] = true;
    }
    index = 917714;
    while (index <= 917953) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *CaseIgnorable) void {
    self.allocator.free(self.array);
}

// isCaseIgnorable checks if cp is of the kind Case_Ignorable.
pub fn isCaseIgnorable(self: CaseIgnorable, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
