// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Cased code points.

const std = @import("std");
const mem = std.mem;

const Cased = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 39,
hi: u21 = 127369,

pub fn init(allocator: *mem.Allocator) !Cased {
    var instance = Cased{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 127331),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 26;
    while (index <= 51) : (index += 1) {
        instance.array[index] = true;
    }
    index = 58;
    while (index <= 83) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[131] = true;
    instance.array[142] = true;
    instance.array[147] = true;
    index = 153;
    while (index <= 175) : (index += 1) {
        instance.array[index] = true;
    }
    index = 177;
    while (index <= 207) : (index += 1) {
        instance.array[index] = true;
    }
    index = 209;
    while (index <= 403) : (index += 1) {
        instance.array[index] = true;
    }
    index = 405;
    while (index <= 408) : (index += 1) {
        instance.array[index] = true;
    }
    index = 413;
    while (index <= 620) : (index += 1) {
        instance.array[index] = true;
    }
    index = 622;
    while (index <= 648) : (index += 1) {
        instance.array[index] = true;
    }
    index = 649;
    while (index <= 657) : (index += 1) {
        instance.array[index] = true;
    }
    index = 665;
    while (index <= 666) : (index += 1) {
        instance.array[index] = true;
    }
    index = 697;
    while (index <= 701) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[798] = true;
    index = 841;
    while (index <= 844) : (index += 1) {
        instance.array[index] = true;
    }
    index = 847;
    while (index <= 848) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[851] = true;
    index = 852;
    while (index <= 854) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[856] = true;
    instance.array[863] = true;
    index = 865;
    while (index <= 867) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[869] = true;
    index = 871;
    while (index <= 890) : (index += 1) {
        instance.array[index] = true;
    }
    index = 892;
    while (index <= 974) : (index += 1) {
        instance.array[index] = true;
    }
    index = 976;
    while (index <= 1114) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1123;
    while (index <= 1288) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1290;
    while (index <= 1327) : (index += 1) {
        instance.array[index] = true;
    }
    index = 1337;
    while (index <= 1377) : (index += 1) {
        instance.array[index] = true;
    }
    index = 4217;
    while (index <= 4254) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[4256] = true;
    instance.array[4262] = true;
    index = 4265;
    while (index <= 4307) : (index += 1) {
        instance.array[index] = true;
    }
    index = 4310;
    while (index <= 4312) : (index += 1) {
        instance.array[index] = true;
    }
    index = 4985;
    while (index <= 5070) : (index += 1) {
        instance.array[index] = true;
    }
    index = 5073;
    while (index <= 5078) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7257;
    while (index <= 7265) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7273;
    while (index <= 7315) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7318;
    while (index <= 7320) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7385;
    while (index <= 7428) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7429;
    while (index <= 7491) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7492;
    while (index <= 7504) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[7505] = true;
    index = 7506;
    while (index <= 7539) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7540;
    while (index <= 7576) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7641;
    while (index <= 7918) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7921;
    while (index <= 7926) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7929;
    while (index <= 7966) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7969;
    while (index <= 7974) : (index += 1) {
        instance.array[index] = true;
    }
    index = 7977;
    while (index <= 7984) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[7986] = true;
    instance.array[7988] = true;
    instance.array[7990] = true;
    index = 7992;
    while (index <= 8022) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8025;
    while (index <= 8077) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8079;
    while (index <= 8085) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8087] = true;
    index = 8091;
    while (index <= 8093) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8095;
    while (index <= 8101) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8105;
    while (index <= 8108) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8111;
    while (index <= 8116) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8121;
    while (index <= 8133) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8139;
    while (index <= 8141) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8143;
    while (index <= 8149) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8266] = true;
    instance.array[8280] = true;
    index = 8297;
    while (index <= 8309) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8411] = true;
    instance.array[8416] = true;
    index = 8419;
    while (index <= 8428) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8430] = true;
    index = 8434;
    while (index <= 8438) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8445] = true;
    instance.array[8447] = true;
    instance.array[8449] = true;
    index = 8451;
    while (index <= 8454) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8456;
    while (index <= 8461) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8466] = true;
    index = 8469;
    while (index <= 8472) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8478;
    while (index <= 8482) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[8487] = true;
    index = 8505;
    while (index <= 8536) : (index += 1) {
        instance.array[index] = true;
    }
    index = 8540;
    while (index <= 8541) : (index += 1) {
        instance.array[index] = true;
    }
    index = 9359;
    while (index <= 9410) : (index += 1) {
        instance.array[index] = true;
    }
    index = 11225;
    while (index <= 11271) : (index += 1) {
        instance.array[index] = true;
    }
    index = 11273;
    while (index <= 11319) : (index += 1) {
        instance.array[index] = true;
    }
    index = 11321;
    while (index <= 11348) : (index += 1) {
        instance.array[index] = true;
    }
    index = 11349;
    while (index <= 11350) : (index += 1) {
        instance.array[index] = true;
    }
    index = 11351;
    while (index <= 11453) : (index += 1) {
        instance.array[index] = true;
    }
    index = 11460;
    while (index <= 11463) : (index += 1) {
        instance.array[index] = true;
    }
    index = 11467;
    while (index <= 11468) : (index += 1) {
        instance.array[index] = true;
    }
    index = 11481;
    while (index <= 11518) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[11520] = true;
    instance.array[11526] = true;
    index = 42521;
    while (index <= 42566) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42585;
    while (index <= 42612) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42613;
    while (index <= 42614) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42747;
    while (index <= 42824) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42825] = true;
    index = 42826;
    while (index <= 42848) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42852;
    while (index <= 42855) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42857;
    while (index <= 42904) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42907;
    while (index <= 42915) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42958;
    while (index <= 42959) : (index += 1) {
        instance.array[index] = true;
    }
    index = 42961;
    while (index <= 42962) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[42963] = true;
    index = 43785;
    while (index <= 43827) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43829;
    while (index <= 43832) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43833;
    while (index <= 43841) : (index += 1) {
        instance.array[index] = true;
    }
    index = 43849;
    while (index <= 43928) : (index += 1) {
        instance.array[index] = true;
    }
    index = 64217;
    while (index <= 64223) : (index += 1) {
        instance.array[index] = true;
    }
    index = 64236;
    while (index <= 64240) : (index += 1) {
        instance.array[index] = true;
    }
    index = 65274;
    while (index <= 65299) : (index += 1) {
        instance.array[index] = true;
    }
    index = 65306;
    while (index <= 65331) : (index += 1) {
        instance.array[index] = true;
    }
    index = 66521;
    while (index <= 66600) : (index += 1) {
        instance.array[index] = true;
    }
    index = 66697;
    while (index <= 66732) : (index += 1) {
        instance.array[index] = true;
    }
    index = 66737;
    while (index <= 66772) : (index += 1) {
        instance.array[index] = true;
    }
    index = 68697;
    while (index <= 68747) : (index += 1) {
        instance.array[index] = true;
    }
    index = 68761;
    while (index <= 68811) : (index += 1) {
        instance.array[index] = true;
    }
    index = 71801;
    while (index <= 71864) : (index += 1) {
        instance.array[index] = true;
    }
    index = 93721;
    while (index <= 93784) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119769;
    while (index <= 119853) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119855;
    while (index <= 119925) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119927;
    while (index <= 119928) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[119931] = true;
    index = 119934;
    while (index <= 119935) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119938;
    while (index <= 119941) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119943;
    while (index <= 119954) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[119956] = true;
    index = 119958;
    while (index <= 119964) : (index += 1) {
        instance.array[index] = true;
    }
    index = 119966;
    while (index <= 120030) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120032;
    while (index <= 120035) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120038;
    while (index <= 120045) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120047;
    while (index <= 120053) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120055;
    while (index <= 120082) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120084;
    while (index <= 120087) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120089;
    while (index <= 120093) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[120095] = true;
    index = 120099;
    while (index <= 120105) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120107;
    while (index <= 120446) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120449;
    while (index <= 120473) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120475;
    while (index <= 120499) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120501;
    while (index <= 120531) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120533;
    while (index <= 120557) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120559;
    while (index <= 120589) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120591;
    while (index <= 120615) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120617;
    while (index <= 120647) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120649;
    while (index <= 120673) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120675;
    while (index <= 120705) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120707;
    while (index <= 120731) : (index += 1) {
        instance.array[index] = true;
    }
    index = 120733;
    while (index <= 120740) : (index += 1) {
        instance.array[index] = true;
    }
    index = 125145;
    while (index <= 125212) : (index += 1) {
        instance.array[index] = true;
    }
    index = 127241;
    while (index <= 127266) : (index += 1) {
        instance.array[index] = true;
    }
    index = 127273;
    while (index <= 127298) : (index += 1) {
        instance.array[index] = true;
    }
    index = 127305;
    while (index <= 127330) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Cased) void {
    self.allocator.free(self.array);
}

// isCased checks if cp is of the kind Cased.
pub fn isCased(self: Cased, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
