// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//! Unicode combining class mapping.

const std = @import("std");
const mem = std.mem;

const CccMap = @This();

allocator: *mem.Allocator,
map: std.AutoHashMap(u21, u8),

const Singleton = struct {
    instance: *CccMap,
    ref_count: usize,
};

var singleton: ?Singleton = null;

pub fn init(allocator: *mem.Allocator) !*CccMap {
    if (singleton) |*s| {
        s.ref_count += 1;
        return s.instance;
    }

    var instance = try allocator.create(CccMap);

    instance.* = CccMap{
        .allocator = allocator,
        .map = std.AutoHashMap(u21, u8).init(allocator),
    };

    var index: u21 = 0;

    index = 0x0334;
    while (index <= 0x0338) : (index += 1) {
        try instance.map.put(index, 1);
    }
    try instance.map.put(0x1CD4, 1);
    index = 0x1CE2;
    while (index <= 0x1CE8) : (index += 1) {
        try instance.map.put(index, 1);
    }
    index = 0x20D2;
    while (index <= 0x20D3) : (index += 1) {
        try instance.map.put(index, 1);
    }
    index = 0x20D8;
    while (index <= 0x20DA) : (index += 1) {
        try instance.map.put(index, 1);
    }
    index = 0x20E5;
    while (index <= 0x20E6) : (index += 1) {
        try instance.map.put(index, 1);
    }
    index = 0x20EA;
    while (index <= 0x20EB) : (index += 1) {
        try instance.map.put(index, 1);
    }
    try instance.map.put(0x10A39, 1);
    index = 0x16AF0;
    while (index <= 0x16AF4) : (index += 1) {
        try instance.map.put(index, 1);
    }
    try instance.map.put(0x1BC9E, 1);
    index = 0x1D167;
    while (index <= 0x1D169) : (index += 1) {
        try instance.map.put(index, 1);
    }
    index = 0x16FF0;
    while (index <= 0x16FF1) : (index += 1) {
        try instance.map.put(index, 6);
    }
    try instance.map.put(0x093C, 7);
    try instance.map.put(0x09BC, 7);
    try instance.map.put(0x0A3C, 7);
    try instance.map.put(0x0ABC, 7);
    try instance.map.put(0x0B3C, 7);
    try instance.map.put(0x0CBC, 7);
    try instance.map.put(0x1037, 7);
    try instance.map.put(0x1B34, 7);
    try instance.map.put(0x1BE6, 7);
    try instance.map.put(0x1C37, 7);
    try instance.map.put(0xA9B3, 7);
    try instance.map.put(0x110BA, 7);
    try instance.map.put(0x11173, 7);
    try instance.map.put(0x111CA, 7);
    try instance.map.put(0x11236, 7);
    try instance.map.put(0x112E9, 7);
    index = 0x1133B;
    while (index <= 0x1133C) : (index += 1) {
        try instance.map.put(index, 7);
    }
    try instance.map.put(0x11446, 7);
    try instance.map.put(0x114C3, 7);
    try instance.map.put(0x115C0, 7);
    try instance.map.put(0x116B7, 7);
    try instance.map.put(0x1183A, 7);
    try instance.map.put(0x11943, 7);
    try instance.map.put(0x11D42, 7);
    try instance.map.put(0x1E94A, 7);
    index = 0x3099;
    while (index <= 0x309A) : (index += 1) {
        try instance.map.put(index, 8);
    }
    try instance.map.put(0x094D, 9);
    try instance.map.put(0x09CD, 9);
    try instance.map.put(0x0A4D, 9);
    try instance.map.put(0x0ACD, 9);
    try instance.map.put(0x0B4D, 9);
    try instance.map.put(0x0BCD, 9);
    try instance.map.put(0x0C4D, 9);
    try instance.map.put(0x0CCD, 9);
    index = 0x0D3B;
    while (index <= 0x0D3C) : (index += 1) {
        try instance.map.put(index, 9);
    }
    try instance.map.put(0x0D4D, 9);
    try instance.map.put(0x0DCA, 9);
    try instance.map.put(0x0E3A, 9);
    try instance.map.put(0x0EBA, 9);
    try instance.map.put(0x0F84, 9);
    index = 0x1039;
    while (index <= 0x103A) : (index += 1) {
        try instance.map.put(index, 9);
    }
    try instance.map.put(0x1714, 9);
    try instance.map.put(0x1734, 9);
    try instance.map.put(0x17D2, 9);
    try instance.map.put(0x1A60, 9);
    try instance.map.put(0x1B44, 9);
    try instance.map.put(0x1BAA, 9);
    try instance.map.put(0x1BAB, 9);
    index = 0x1BF2;
    while (index <= 0x1BF3) : (index += 1) {
        try instance.map.put(index, 9);
    }
    try instance.map.put(0x2D7F, 9);
    try instance.map.put(0xA806, 9);
    try instance.map.put(0xA82C, 9);
    try instance.map.put(0xA8C4, 9);
    try instance.map.put(0xA953, 9);
    try instance.map.put(0xA9C0, 9);
    try instance.map.put(0xAAF6, 9);
    try instance.map.put(0xABED, 9);
    try instance.map.put(0x10A3F, 9);
    try instance.map.put(0x11046, 9);
    try instance.map.put(0x1107F, 9);
    try instance.map.put(0x110B9, 9);
    index = 0x11133;
    while (index <= 0x11134) : (index += 1) {
        try instance.map.put(index, 9);
    }
    try instance.map.put(0x111C0, 9);
    try instance.map.put(0x11235, 9);
    try instance.map.put(0x112EA, 9);
    try instance.map.put(0x1134D, 9);
    try instance.map.put(0x11442, 9);
    try instance.map.put(0x114C2, 9);
    try instance.map.put(0x115BF, 9);
    try instance.map.put(0x1163F, 9);
    try instance.map.put(0x116B6, 9);
    try instance.map.put(0x1172B, 9);
    try instance.map.put(0x11839, 9);
    try instance.map.put(0x1193D, 9);
    try instance.map.put(0x1193E, 9);
    try instance.map.put(0x119E0, 9);
    try instance.map.put(0x11A34, 9);
    try instance.map.put(0x11A47, 9);
    try instance.map.put(0x11A99, 9);
    try instance.map.put(0x11C3F, 9);
    index = 0x11D44;
    while (index <= 0x11D45) : (index += 1) {
        try instance.map.put(index, 9);
    }
    try instance.map.put(0x11D97, 9);
    try instance.map.put(0x05B0, 10);
    try instance.map.put(0x05B1, 11);
    try instance.map.put(0x05B2, 12);
    try instance.map.put(0x05B3, 13);
    try instance.map.put(0x05B4, 14);
    try instance.map.put(0x05B5, 15);
    try instance.map.put(0x05B6, 16);
    try instance.map.put(0x05B7, 17);
    try instance.map.put(0x05B8, 18);
    try instance.map.put(0x05C7, 18);
    index = 0x05B9;
    while (index <= 0x05BA) : (index += 1) {
        try instance.map.put(index, 19);
    }
    try instance.map.put(0x05BB, 20);
    try instance.map.put(0x05BC, 21);
    try instance.map.put(0x05BD, 22);
    try instance.map.put(0x05BF, 23);
    try instance.map.put(0x05C1, 24);
    try instance.map.put(0x05C2, 25);
    try instance.map.put(0xFB1E, 26);
    try instance.map.put(0x064B, 27);
    try instance.map.put(0x08F0, 27);
    try instance.map.put(0x064C, 28);
    try instance.map.put(0x08F1, 28);
    try instance.map.put(0x064D, 29);
    try instance.map.put(0x08F2, 29);
    try instance.map.put(0x0618, 30);
    try instance.map.put(0x064E, 30);
    try instance.map.put(0x0619, 31);
    try instance.map.put(0x064F, 31);
    try instance.map.put(0x061A, 32);
    try instance.map.put(0x0650, 32);
    try instance.map.put(0x0651, 33);
    try instance.map.put(0x0652, 34);
    try instance.map.put(0x0670, 35);
    try instance.map.put(0x0711, 36);
    try instance.map.put(0x0C55, 84);
    try instance.map.put(0x0C56, 91);
    index = 0x0E38;
    while (index <= 0x0E39) : (index += 1) {
        try instance.map.put(index, 103);
    }
    index = 0x0E48;
    while (index <= 0x0E4B) : (index += 1) {
        try instance.map.put(index, 107);
    }
    index = 0x0EB8;
    while (index <= 0x0EB9) : (index += 1) {
        try instance.map.put(index, 118);
    }
    index = 0x0EC8;
    while (index <= 0x0ECB) : (index += 1) {
        try instance.map.put(index, 122);
    }
    try instance.map.put(0x0F71, 129);
    try instance.map.put(0x0F72, 130);
    index = 0x0F7A;
    while (index <= 0x0F7D) : (index += 1) {
        try instance.map.put(index, 130);
    }
    try instance.map.put(0x0F80, 130);
    try instance.map.put(0x0F74, 132);
    index = 0x0321;
    while (index <= 0x0322) : (index += 1) {
        try instance.map.put(index, 202);
    }
    index = 0x0327;
    while (index <= 0x0328) : (index += 1) {
        try instance.map.put(index, 202);
    }
    try instance.map.put(0x1DD0, 202);
    try instance.map.put(0x1DCE, 214);
    try instance.map.put(0x031B, 216);
    try instance.map.put(0x0F39, 216);
    index = 0x1D165;
    while (index <= 0x1D166) : (index += 1) {
        try instance.map.put(index, 216);
    }
    index = 0x1D16E;
    while (index <= 0x1D172) : (index += 1) {
        try instance.map.put(index, 216);
    }
    try instance.map.put(0x302A, 218);
    index = 0x0316;
    while (index <= 0x0319) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x031C;
    while (index <= 0x0320) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x0323;
    while (index <= 0x0326) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x0329;
    while (index <= 0x0333) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x0339;
    while (index <= 0x033C) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x0347;
    while (index <= 0x0349) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x034D;
    while (index <= 0x034E) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x0353;
    while (index <= 0x0356) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x0359;
    while (index <= 0x035A) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x0591, 220);
    try instance.map.put(0x0596, 220);
    try instance.map.put(0x059B, 220);
    index = 0x05A2;
    while (index <= 0x05A7) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x05AA, 220);
    try instance.map.put(0x05C5, 220);
    index = 0x0655;
    while (index <= 0x0656) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x065C, 220);
    try instance.map.put(0x065F, 220);
    try instance.map.put(0x06E3, 220);
    try instance.map.put(0x06EA, 220);
    try instance.map.put(0x06ED, 220);
    try instance.map.put(0x0731, 220);
    try instance.map.put(0x0734, 220);
    index = 0x0737;
    while (index <= 0x0739) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x073B;
    while (index <= 0x073C) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x073E, 220);
    try instance.map.put(0x0742, 220);
    try instance.map.put(0x0744, 220);
    try instance.map.put(0x0746, 220);
    try instance.map.put(0x0748, 220);
    try instance.map.put(0x07F2, 220);
    try instance.map.put(0x07FD, 220);
    index = 0x0859;
    while (index <= 0x085B) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x08D3, 220);
    try instance.map.put(0x08E3, 220);
    try instance.map.put(0x08E6, 220);
    try instance.map.put(0x08E9, 220);
    index = 0x08ED;
    while (index <= 0x08EF) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x08F6, 220);
    index = 0x08F9;
    while (index <= 0x08FA) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x0952, 220);
    index = 0x0F18;
    while (index <= 0x0F19) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x0F35, 220);
    try instance.map.put(0x0F37, 220);
    try instance.map.put(0x0FC6, 220);
    try instance.map.put(0x108D, 220);
    try instance.map.put(0x193B, 220);
    try instance.map.put(0x1A18, 220);
    try instance.map.put(0x1A7F, 220);
    index = 0x1AB5;
    while (index <= 0x1ABA) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x1ABD, 220);
    index = 0x1ABF;
    while (index <= 0x1AC0) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x1B6C, 220);
    index = 0x1CD5;
    while (index <= 0x1CD9) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x1CDC;
    while (index <= 0x1CDF) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x1CED, 220);
    try instance.map.put(0x1DC2, 220);
    try instance.map.put(0x1DCA, 220);
    try instance.map.put(0x1DCF, 220);
    try instance.map.put(0x1DF9, 220);
    try instance.map.put(0x1DFD, 220);
    try instance.map.put(0x1DFF, 220);
    try instance.map.put(0x20E8, 220);
    index = 0x20EC;
    while (index <= 0x20EF) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0xA92B;
    while (index <= 0xA92D) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0xAAB4, 220);
    index = 0xFE27;
    while (index <= 0xFE2D) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x101FD, 220);
    try instance.map.put(0x102E0, 220);
    try instance.map.put(0x10A0D, 220);
    try instance.map.put(0x10A3A, 220);
    try instance.map.put(0x10AE6, 220);
    index = 0x10F46;
    while (index <= 0x10F47) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x10F4B, 220);
    index = 0x10F4D;
    while (index <= 0x10F50) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x1D17B;
    while (index <= 0x1D182) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x1D18A;
    while (index <= 0x1D18B) : (index += 1) {
        try instance.map.put(index, 220);
    }
    index = 0x1E8D0;
    while (index <= 0x1E8D6) : (index += 1) {
        try instance.map.put(index, 220);
    }
    try instance.map.put(0x059A, 222);
    try instance.map.put(0x05AD, 222);
    try instance.map.put(0x1939, 222);
    try instance.map.put(0x302D, 222);
    index = 0x302E;
    while (index <= 0x302F) : (index += 1) {
        try instance.map.put(index, 224);
    }
    try instance.map.put(0x1D16D, 226);
    try instance.map.put(0x05AE, 228);
    try instance.map.put(0x18A9, 228);
    index = 0x1DF7;
    while (index <= 0x1DF8) : (index += 1) {
        try instance.map.put(index, 228);
    }
    try instance.map.put(0x302B, 228);
    index = 0x0300;
    while (index <= 0x0314) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x033D;
    while (index <= 0x0344) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x0346, 230);
    index = 0x034A;
    while (index <= 0x034C) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x0350;
    while (index <= 0x0352) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x0357, 230);
    try instance.map.put(0x035B, 230);
    index = 0x0363;
    while (index <= 0x036F) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x0483;
    while (index <= 0x0487) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x0592;
    while (index <= 0x0595) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x0597;
    while (index <= 0x0599) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x059C;
    while (index <= 0x05A1) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x05A8;
    while (index <= 0x05A9) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x05AB;
    while (index <= 0x05AC) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x05AF, 230);
    try instance.map.put(0x05C4, 230);
    index = 0x0610;
    while (index <= 0x0617) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x0653;
    while (index <= 0x0654) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x0657;
    while (index <= 0x065B) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x065D;
    while (index <= 0x065E) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x06D6;
    while (index <= 0x06DC) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x06DF;
    while (index <= 0x06E2) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x06E4, 230);
    index = 0x06E7;
    while (index <= 0x06E8) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x06EB;
    while (index <= 0x06EC) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x0730, 230);
    index = 0x0732;
    while (index <= 0x0733) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x0735;
    while (index <= 0x0736) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x073A, 230);
    try instance.map.put(0x073D, 230);
    index = 0x073F;
    while (index <= 0x0741) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x0743, 230);
    try instance.map.put(0x0745, 230);
    try instance.map.put(0x0747, 230);
    index = 0x0749;
    while (index <= 0x074A) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x07EB;
    while (index <= 0x07F1) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x07F3, 230);
    index = 0x0816;
    while (index <= 0x0819) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x081B;
    while (index <= 0x0823) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x0825;
    while (index <= 0x0827) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x0829;
    while (index <= 0x082D) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x08D4;
    while (index <= 0x08E1) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x08E4;
    while (index <= 0x08E5) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x08E7;
    while (index <= 0x08E8) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x08EA;
    while (index <= 0x08EC) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x08F3;
    while (index <= 0x08F5) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x08F7;
    while (index <= 0x08F8) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x08FB;
    while (index <= 0x08FF) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x0951, 230);
    index = 0x0953;
    while (index <= 0x0954) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x09FE, 230);
    index = 0x0F82;
    while (index <= 0x0F83) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x0F86;
    while (index <= 0x0F87) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x135D;
    while (index <= 0x135F) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x17DD, 230);
    try instance.map.put(0x193A, 230);
    try instance.map.put(0x1A17, 230);
    index = 0x1A75;
    while (index <= 0x1A7C) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1AB0;
    while (index <= 0x1AB4) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1ABB;
    while (index <= 0x1ABC) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x1B6B, 230);
    index = 0x1B6D;
    while (index <= 0x1B73) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1CD0;
    while (index <= 0x1CD2) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1CDA;
    while (index <= 0x1CDB) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x1CE0, 230);
    try instance.map.put(0x1CF4, 230);
    index = 0x1CF8;
    while (index <= 0x1CF9) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1DC0;
    while (index <= 0x1DC1) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1DC3;
    while (index <= 0x1DC9) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1DCB;
    while (index <= 0x1DCC) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1DD1;
    while (index <= 0x1DF5) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x1DFB, 230);
    try instance.map.put(0x1DFE, 230);
    index = 0x20D0;
    while (index <= 0x20D1) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x20D4;
    while (index <= 0x20D7) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x20DB;
    while (index <= 0x20DC) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x20E1, 230);
    try instance.map.put(0x20E7, 230);
    try instance.map.put(0x20E9, 230);
    try instance.map.put(0x20F0, 230);
    index = 0x2CEF;
    while (index <= 0x2CF1) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x2DE0;
    while (index <= 0x2DFF) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0xA66F, 230);
    index = 0xA674;
    while (index <= 0xA67D) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0xA69E;
    while (index <= 0xA69F) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0xA6F0;
    while (index <= 0xA6F1) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0xA8E0;
    while (index <= 0xA8F1) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0xAAB0, 230);
    index = 0xAAB2;
    while (index <= 0xAAB3) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0xAAB7;
    while (index <= 0xAAB8) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0xAABE;
    while (index <= 0xAABF) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0xAAC1, 230);
    index = 0xFE20;
    while (index <= 0xFE26) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0xFE2E;
    while (index <= 0xFE2F) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x10376;
    while (index <= 0x1037A) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x10A0F, 230);
    try instance.map.put(0x10A38, 230);
    try instance.map.put(0x10AE5, 230);
    index = 0x10D24;
    while (index <= 0x10D27) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x10EAB;
    while (index <= 0x10EAC) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x10F48;
    while (index <= 0x10F4A) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x10F4C, 230);
    index = 0x11100;
    while (index <= 0x11102) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x11366;
    while (index <= 0x1136C) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x11370;
    while (index <= 0x11374) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x1145E, 230);
    index = 0x16B30;
    while (index <= 0x16B36) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1D185;
    while (index <= 0x1D189) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1D1AA;
    while (index <= 0x1D1AD) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1D242;
    while (index <= 0x1D244) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1E000;
    while (index <= 0x1E006) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1E008;
    while (index <= 0x1E018) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1E01B;
    while (index <= 0x1E021) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1E023;
    while (index <= 0x1E024) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1E026;
    while (index <= 0x1E02A) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1E130;
    while (index <= 0x1E136) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1E2EC;
    while (index <= 0x1E2EF) : (index += 1) {
        try instance.map.put(index, 230);
    }
    index = 0x1E944;
    while (index <= 0x1E949) : (index += 1) {
        try instance.map.put(index, 230);
    }
    try instance.map.put(0x0315, 232);
    try instance.map.put(0x031A, 232);
    try instance.map.put(0x0358, 232);
    try instance.map.put(0x1DF6, 232);
    try instance.map.put(0x302C, 232);
    try instance.map.put(0x035C, 233);
    try instance.map.put(0x035F, 233);
    try instance.map.put(0x0362, 233);
    try instance.map.put(0x1DFC, 233);
    index = 0x035D;
    while (index <= 0x035E) : (index += 1) {
        try instance.map.put(index, 234);
    }
    index = 0x0360;
    while (index <= 0x0361) : (index += 1) {
        try instance.map.put(index, 234);
    }
    try instance.map.put(0x1DCD, 234);
    try instance.map.put(0x0345, 240);
    singleton = Singleton{
        .instance = instance,
        .ref_count = 1,
    };

    return instance;
}

pub fn deinit(self: *CccMap) void {
    self.map.deinit();
    if (singleton) |*s| {
        s.ref_count -= 1;
        if (s.ref_count == 0) {
            self.allocator.destroy(s.instance);
            singleton = null;
        }
    }
}

/// combiningClass maps the code point to its combining class value.
pub fn combiningClass(self: CccMap, cp: u21) u8 {
    return if (self.map.get(cp)) |cc| cc else 0;
}
