// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Arabic Presentation Forms-B code points.

const std = @import("std");
const mem = std.mem;

const ArabicPresentationFormsBª = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 0,
hi: u21 = 65279,

pub fn init(allocator: *mem.Allocator) !ArabicPresentationFormsBª {
    var instance = ArabicPresentationFormsBª{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 65280),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 65136;
    while (index <= 65279) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *ArabicPresentationFormsBª) void {
    self.allocator.free(self.array);
}

// isArabicPresentationFormsBª checks if cp is of the kind Arabic Presentation Forms-B.
pub fn isArabicPresentationFormsBª(self: ArabicPresentationFormsBª, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
