// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Arrows code points.

const std = @import("std");
const mem = std.mem;

const Arrows = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 8592,
hi: u21 = 8703,

pub fn init(allocator: *mem.Allocator) !Arrows {
    var instance = Arrows{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 112),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 0;
    while (index <= 111) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Arrows) void {
    self.allocator.free(self.array);
}

// isArrows checks if cp is of the kind Arrows.
pub fn isArrows(self: Arrows, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
