// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Carian code points.

const std = @import("std");
const mem = std.mem;

const Carian = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 0,
hi: u21 = 66271,

pub fn init(allocator: *mem.Allocator) !Carian {
    var instance = Carian{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 66272),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 66208;
    while (index <= 66271) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Carian) void {
    self.allocator.free(self.array);
}

// isCarian checks if cp is of the kind Carian.
pub fn isCarian(self: Carian, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
