// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Currency Symbols code points.

const std = @import("std");
const mem = std.mem;

const CurrencySymbols = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 0,
hi: u21 = 8399,

pub fn init(allocator: *mem.Allocator) !CurrencySymbols {
    var instance = CurrencySymbols{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 8400),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 8352;
    while (index <= 8399) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *CurrencySymbols) void {
    self.allocator.free(self.array);
}

// isCurrencySymbols checks if cp is of the kind Currency Symbols.
pub fn isCurrencySymbols(self: CurrencySymbols, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
