// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Hatran code points.

const std = @import("std");
const mem = std.mem;

const Hatran = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 67808,
hi: u21 = 67839,

pub fn init(allocator: *mem.Allocator) !Hatran {
    var instance = Hatran{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 32),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 0;
    while (index <= 31) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Hatran) void {
    self.allocator.free(self.array);
}

// isHatran checks if cp is of the kind Hatran.
pub fn isHatran(self: Hatran, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
