// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Tags code points.

const std = @import("std");
const mem = std.mem;

const Tags = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 0,
hi: u21 = 917631,

pub fn init(allocator: *mem.Allocator) !Tags {
    var instance = Tags{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 917632),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    index = 917504;
    while (index <= 917631) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Tags) void {
    self.allocator.free(self.array);
}

// isTags checks if cp is of the kind Tags.
pub fn isTags(self: Tags, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
