// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Medial code points.

const std = @import("std");
const mem = std.mem;

const Medial = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 64341,
hi: u21 = 65268,

pub fn init(allocator: *mem.Allocator) !Medial {
    var instance = Medial{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 928),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    instance.array[0] = true;
    instance.array[4] = true;
    instance.array[8] = true;
    instance.array[12] = true;
    instance.array[16] = true;
    instance.array[20] = true;
    instance.array[24] = true;
    instance.array[28] = true;
    instance.array[32] = true;
    instance.array[36] = true;
    instance.array[40] = true;
    instance.array[44] = true;
    instance.array[60] = true;
    instance.array[64] = true;
    instance.array[68] = true;
    instance.array[72] = true;
    instance.array[78] = true;
    instance.array[84] = true;
    instance.array[88] = true;
    instance.array[129] = true;
    instance.array[146] = true;
    instance.array[148] = true;
    instance.array[170] = true;
    index = 394;
    while (index <= 415) : (index += 1) {
        instance.array[index] = true;
    }
    index = 479;
    while (index <= 486) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[796] = true;
    instance.array[802] = true;
    instance.array[804] = true;
    instance.array[806] = true;
    instance.array[808] = true;
    instance.array[810] = true;
    instance.array[823] = true;
    instance.array[829] = true;
    instance.array[835] = true;
    instance.array[839] = true;
    instance.array[843] = true;
    instance.array[847] = true;
    instance.array[851] = true;
    instance.array[863] = true;
    instance.array[867] = true;
    instance.array[871] = true;
    instance.array[875] = true;
    instance.array[879] = true;
    instance.array[883] = true;
    instance.array[887] = true;
    instance.array[891] = true;
    instance.array[895] = true;
    instance.array[899] = true;
    instance.array[903] = true;
    instance.array[907] = true;
    instance.array[911] = true;
    instance.array[915] = true;
    instance.array[919] = true;
    instance.array[927] = true;

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Medial) void {
    self.allocator.free(self.array);
}

// isMedial checks if cp is of the kind Medial.
pub fn isMedial(self: Medial, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
