// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt by running ucd_gen.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Array length
//    3. Highest code point
//    4. Lowest code point
//! Unicode Square code points.

const std = @import("std");
const mem = std.mem;

const Square = @This();

allocator: *mem.Allocator,
array: []bool,
lo: u21 = 12880,
hi: u21 = 127547,

pub fn init(allocator: *mem.Allocator) !Square {
    var instance = Square{
        .allocator = allocator,
        .array = try allocator.alloc(bool, 114668),
    };

    mem.set(bool, instance.array, false);

    var index: u21 = 0;
    instance.array[0] = true;
    index = 124;
    while (index <= 127) : (index += 1) {
        instance.array[index] = true;
    }
    index = 175;
    while (index <= 263) : (index += 1) {
        instance.array[index] = true;
    }
    index = 289;
    while (index <= 399) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[431] = true;
    index = 114400;
    while (index <= 114431) : (index += 1) {
        instance.array[index] = true;
    }
    instance.array[114496] = true;
    index = 114608;
    while (index <= 114610) : (index += 1) {
        instance.array[index] = true;
    }
    index = 114624;
    while (index <= 114667) : (index += 1) {
        instance.array[index] = true;
    }

    // Placeholder: 0. Struct name
    return instance;
}

pub fn deinit(self: *Square) void {
    self.allocator.free(self.array);
}

// isSquare checks if cp is of the kind Square.
pub fn isSquare(self: Square, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    const index = cp - self.lo;
    return if (index >= self.array.len) false else self.array[index];
}
