// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode Prepend code points.

lo: u21 = 1536,
hi: u21 = 73030,

const Prepend = @This();

pub fn isPrepend(self: Prepend, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    return switch (cp) {
        0x600...0x605 => true,
        0x6dd => true,
        0x70f => true,
        0x8e2 => true,
        0xd4e => true,
        0x110bd => true,
        0x110cd => true,
        0x111c2...0x111c3 => true,
        0x1193f => true,
        0x11941 => true,
        0x11a3a => true,
        0x11a84...0x11a89 => true,
        0x11d46 => true,
        else => false,
    };
}