// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Struct name
//    1. Lowest code point
//    2. Highest code point
//! Unicode V code points.

const lo: u21 = 4448;
const hi: u21 = 55238;

pub fn isV(cp: u21) bool {
    if (cp < lo or cp > hi) return false;
    return switch (cp) {
        0x1160...0x11a7 => true,
        0xd7b0...0xd7c6 => true,
        else => false,
    };
}