// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Lowest code point
//    3. Highest code point
//! Unicode Logical_Order_Exception code points.

const std = @import("std");
const mem = std.mem;

const LogicalOrderException = @This();

allocator: *mem.Allocator,
cp_set: std.AutoHashMap(u21, void),
lo: u21 = 3648,
hi: u21 = 43708,

const Singleton = struct {
    instance: *LogicalOrderException,
    ref_count: usize,
};

var singleton: ?Singleton = null;

pub fn init(allocator: *mem.Allocator) !*LogicalOrderException {
    if (singleton) |*s| {
        s.ref_count += 1;
        return s.instance;
    }

    var instance = try allocator.create(LogicalOrderException);

    instance.* = LogicalOrderException{
        .allocator = allocator,
        .cp_set = std.AutoHashMap(u21, void).init(allocator),
    };

    var index: u21 = 0;
    index = 3648;
    while (index <= 3652) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 3776;
    while (index <= 3780) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 6581;
    while (index <= 6583) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(6586, {});
    index = 43701;
    while (index <= 43702) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(43705, {});
    index = 43707;
    while (index <= 43708) : (index += 1) {
        try instance.cp_set.put(index, {});
    }

    // Placeholder: 0. Struct name, 1. Code point kind
    singleton = Singleton{
        .instance = instance,
        .ref_count = 1,
    };

    return instance;
}

pub fn deinit(self: *LogicalOrderException) void {
    self.cp_set.deinit();
    if (singleton) |*s| {
        s.ref_count -= 1;
        if (s.ref_count == 0) {
            self.allocator.destroy(s.instance);
            singleton = null;
        }
    }
}

// isLogicalOrderException checks if cp is of the kind Logical_Order_Exception.
pub fn isLogicalOrderException(self: LogicalOrderException, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    return self.cp_set.get(cp) != null;
}
