// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Lowest code point
//    3. Highest code point
//! Unicode Terminal_Punctuation code points.

const std = @import("std");
const mem = std.mem;

const TerminalPunctuation = @This();

allocator: *mem.Allocator,
cp_set: std.AutoHashMap(u21, void),
lo: u21 = 33,
hi: u21 = 121482,

pub fn init(allocator: *mem.Allocator) !TerminalPunctuation {
    var instance = TerminalPunctuation{
        .allocator = allocator,
        .cp_set = std.AutoHashMap(u21, void).init(allocator),
    };

    var index: u21 = 0;
    try instance.cp_set.put(33, {});
    try instance.cp_set.put(44, {});
    try instance.cp_set.put(46, {});
    index = 58;
    while (index <= 59) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(63, {});
    try instance.cp_set.put(894, {});
    try instance.cp_set.put(903, {});
    try instance.cp_set.put(1417, {});
    try instance.cp_set.put(1475, {});
    try instance.cp_set.put(1548, {});
    try instance.cp_set.put(1563, {});
    index = 1566;
    while (index <= 1567) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(1748, {});
    index = 1792;
    while (index <= 1802) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(1804, {});
    index = 2040;
    while (index <= 2041) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 2096;
    while (index <= 2110) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(2142, {});
    index = 2404;
    while (index <= 2405) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 3674;
    while (index <= 3675) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(3848, {});
    index = 3853;
    while (index <= 3858) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 4170;
    while (index <= 4171) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 4961;
    while (index <= 4968) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(5742, {});
    index = 5867;
    while (index <= 5869) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 5941;
    while (index <= 5942) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 6100;
    while (index <= 6102) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(6106, {});
    index = 6146;
    while (index <= 6149) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 6152;
    while (index <= 6153) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 6468;
    while (index <= 6469) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 6824;
    while (index <= 6827) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 7002;
    while (index <= 7003) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 7005;
    while (index <= 7007) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 7227;
    while (index <= 7231) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 7294;
    while (index <= 7295) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 8252;
    while (index <= 8253) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 8263;
    while (index <= 8265) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(11822, {});
    try instance.cp_set.put(11836, {});
    try instance.cp_set.put(11841, {});
    try instance.cp_set.put(11852, {});
    index = 11854;
    while (index <= 11855) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 12289;
    while (index <= 12290) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 42238;
    while (index <= 42239) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 42509;
    while (index <= 42511) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 42739;
    while (index <= 42743) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 43126;
    while (index <= 43127) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 43214;
    while (index <= 43215) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(43311, {});
    index = 43463;
    while (index <= 43465) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 43613;
    while (index <= 43615) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(43743, {});
    index = 43760;
    while (index <= 43761) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(44011, {});
    index = 65104;
    while (index <= 65106) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 65108;
    while (index <= 65111) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(65281, {});
    try instance.cp_set.put(65292, {});
    try instance.cp_set.put(65294, {});
    index = 65306;
    while (index <= 65307) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(65311, {});
    try instance.cp_set.put(65377, {});
    try instance.cp_set.put(65380, {});
    try instance.cp_set.put(66463, {});
    try instance.cp_set.put(66512, {});
    try instance.cp_set.put(67671, {});
    try instance.cp_set.put(67871, {});
    index = 68182;
    while (index <= 68183) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68336;
    while (index <= 68341) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68410;
    while (index <= 68415) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 68505;
    while (index <= 68508) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 69461;
    while (index <= 69465) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 69703;
    while (index <= 69709) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 69822;
    while (index <= 69825) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 69953;
    while (index <= 69955) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 70085;
    while (index <= 70086) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(70093, {});
    index = 70110;
    while (index <= 70111) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 70200;
    while (index <= 70204) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(70313, {});
    index = 70731;
    while (index <= 70733) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 70746;
    while (index <= 70747) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 71106;
    while (index <= 71109) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 71113;
    while (index <= 71127) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 71233;
    while (index <= 71234) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 71484;
    while (index <= 71486) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(72004, {});
    try instance.cp_set.put(72006, {});
    index = 72258;
    while (index <= 72259) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 72347;
    while (index <= 72348) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 72353;
    while (index <= 72354) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 72769;
    while (index <= 72771) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(72817, {});
    index = 73463;
    while (index <= 73464) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 74864;
    while (index <= 74868) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 92782;
    while (index <= 92783) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(92917, {});
    index = 92983;
    while (index <= 92985) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(92996, {});
    index = 93847;
    while (index <= 93848) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(113823, {});
    index = 121479;
    while (index <= 121482) : (index += 1) {
        try instance.cp_set.put(index, {});
    }

    // Placeholder: 0. Struct name, 1. Code point kind
    return instance;
}

pub fn deinit(self: *TerminalPunctuation) void {
    self.cp_set.deinit();
}

// isTerminalPunctuation checks if cp is of the kind Terminal_Punctuation.
pub fn isTerminalPunctuation(self: TerminalPunctuation, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    return self.cp_set.get(cp) != null;
}
