// Autogenerated from http://www.unicode.org/Public/UCD/latest/ucd/UCD.zip by running ucd_gen.sh.
// Placeholders:
//    0. Code point type
//    1. Struct name
//    2. Lowest code point
//    3. Highest code point
//! Unicode Unified_Ideograph code points.

const std = @import("std");
const mem = std.mem;

const UnifiedIdeograph = @This();

allocator: *mem.Allocator,
cp_set: std.AutoHashMap(u21, void),
lo: u21 = 13312,
hi: u21 = 201546,

pub fn init(allocator: *mem.Allocator) !UnifiedIdeograph {
    var instance = UnifiedIdeograph{
        .allocator = allocator,
        .cp_set = std.AutoHashMap(u21, void).init(allocator),
    };

    var index: u21 = 0;
    index = 13312;
    while (index <= 19903) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 19968;
    while (index <= 40956) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 64014;
    while (index <= 64015) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(64017, {});
    index = 64019;
    while (index <= 64020) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    try instance.cp_set.put(64031, {});
    try instance.cp_set.put(64033, {});
    index = 64035;
    while (index <= 64036) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 64039;
    while (index <= 64041) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 131072;
    while (index <= 173789) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 173824;
    while (index <= 177972) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 177984;
    while (index <= 178205) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 178208;
    while (index <= 183969) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 183984;
    while (index <= 191456) : (index += 1) {
        try instance.cp_set.put(index, {});
    }
    index = 196608;
    while (index <= 201546) : (index += 1) {
        try instance.cp_set.put(index, {});
    }

    // Placeholder: 0. Struct name, 1. Code point kind
    return instance;
}

pub fn deinit(self: *UnifiedIdeograph) void {
    self.cp_set.deinit();
}

// isUnifiedIdeograph checks if cp is of the kind Unified_Ideograph.
pub fn isUnifiedIdeograph(self: UnifiedIdeograph, cp: u21) bool {
    if (cp < self.lo or cp > self.hi) return false;
    return self.cp_set.get(cp) != null;
}
